import type { Guide, GuideNode } from '../types/guides';

/**
 * Helper para criar ícones padrão baseado no tipo de nó
 * O usuário não escolhe "icon2.1", mas sim um par de ícones que representam estados
 */
function getDefaultIcons(type: GuideNode['type']): { active: string; inactive: string; meaning?: string } {
  // Por padrão, todos os nós usam os mesmos ícones
  // No futuro, pode-se ter ícones específicos por tipo
  return {
    active: '/icon2.1.png',
    inactive: '/icon2.2.png',
    meaning: type === 'reflection' ? 'reflexão' : type === 'skill' ? 'habilidade' : type === 'experience' ? 'experiência' : 'comportamento',
  };
}

/**
 * Inicializa os 5 guias oficiais do sistema
 */
export function initializeOfficialGuides(): { guides: Guide[]; nodes: GuideNode[] } {
  const now = new Date().toISOString();

  const guides: Guide[] = [
    {
      id: 'social-skills',
      userId: null,
      name: 'Habilidades Sociais (Convivência Humana)',
      description: 'Socializar não é performance. É aprender a estar com outros sem se perder de si.',
      philosophicalNote: 'Nem toda interação exige resposta. Às vezes exige atenção.',
      isOfficial: true,
      initialNodeId: 'social-initial',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'relationships',
      userId: null,
      name: 'Relacionamentos e Afeto',
      description: 'Relacionamento não é conquista. É disposição mútua.',
      philosophicalNote: 'Relacionamento não preenche vazios que não se conhecem.',
      isOfficial: true,
      initialNodeId: 'relationships-initial',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'financial-stability',
      userId: null,
      name: 'Estabilidade Financeira',
      description: 'Dinheiro não é virtude nem pecado. É ferramenta de permanência no mundo.',
      isOfficial: true,
      initialNodeId: 'financial-initial',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'dao-path',
      userId: null,
      name: 'O Caminho do Dao (Viver em Fluxo)',
      description: 'Não controlar tudo. Não abandonar tudo. Apenas agir em harmonia com o momento.',
      isOfficial: true,
      initialNodeId: 'dao-initial',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'creating-meaning',
      userId: null,
      name: 'Criar Sentido (Existência e Expressão)',
      description: 'O sentido não é encontrado. É cultivado.',
      isOfficial: true,
      initialNodeId: 'meaning-initial',
      createdAt: now,
      updatedAt: now,
    },
  ];

  const nodesRaw: GuideNode[] = [
    // GUIA 1: Habilidades Sociais
    {
      id: 'social-initial',
      guideId: 'social-skills',
      parentNodeId: null,
      title: 'Perceber o Outro',
      description: 'Nem toda interação exige resposta. Às vezes exige atenção.',
      type: 'reflection',
      state: 'available',
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    // Ramo A - Comunicação Básica
    {
      id: 'social-comm-1',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Ouvir sem preparar resposta',
      description: 'Praticar escuta ativa, focando no que o outro diz sem pensar na resposta.',
      type: 'experience',
      state: 'locked',
      order: 1,
      branch: 'Ramo A — Comunicação Básica',
      icon: getDefaultIcons('experience'),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-comm-2',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Manter contato visual por alguns segundos',
      description: 'Praticar presença através do olhar.',
      type: 'experience',
      state: 'locked',
      order: 2,
      branch: 'Ramo A — Comunicação Básica',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-comm-3',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Responder com curiosidade, não defesa',
      description: 'Transformar reações defensivas em perguntas genuínas.',
      type: 'skill',
      state: 'locked',
      order: 3,
      branch: 'Ramo A — Comunicação Básica',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-comm-4',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Expressar discordância sem ataque',
      description: 'Aprender a discordar mantendo respeito e conexão.',
      type: 'skill',
      state: 'locked',
      order: 4,
      branch: 'Ramo A — Comunicação Básica',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo B - Convivência
    {
      id: 'social-conv-1',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Iniciar conversas simples',
      description: 'Praticar iniciar interações sem pressão de performance.',
      type: 'experience',
      state: 'locked',
      order: 5,
      branch: 'Ramo B — Convivência',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-conv-2',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Aceitar silêncios',
      description: 'Não preencher todos os espaços vazios com palavras.',
      type: 'reflection',
      state: 'locked',
      order: 6,
      branch: 'Ramo B — Convivência',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-conv-3',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Participar de grupos pequenos',
      description: 'Praticar presença em contextos sociais menores.',
      type: 'experience',
      state: 'locked',
      order: 7,
      branch: 'Ramo B — Convivência',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-conv-4',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Saber encerrar interações',
      description: 'Aprender a terminar conversas de forma natural e respeitosa.',
      type: 'skill',
      state: 'locked',
      order: 8,
      branch: 'Ramo B — Convivência',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo C - Interno
    {
      id: 'social-internal-1',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Reconhecer ansiedade social',
      description: 'Identificar quando a ansiedade aparece e entender suas origens.',
      type: 'reflection',
      state: 'locked',
      order: 9,
      branch: 'Ramo C — Interno',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-internal-2',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Diferenciar rejeição de desinteresse',
      description: 'Não personalizar comportamentos que não são sobre você.',
      type: 'reflection',
      state: 'locked',
      order: 10,
      branch: 'Ramo C — Interno',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'social-internal-3',
      guideId: 'social-skills',
      parentNodeId: 'social-initial',
      title: 'Não se definir por uma interação',
      description: 'Uma interação ruim não define quem você é.',
      type: 'reflection',
      state: 'locked',
      order: 11,
      branch: 'Ramo C — Interno',
      createdAt: now,
      updatedAt: now,
    },

    // GUIA 2: Relacionamentos
    {
      id: 'relationships-initial',
      guideId: 'relationships',
      parentNodeId: null,
      title: 'Estar bem só',
      description: 'Relacionamento não preenche vazios que não se conhecem.',
      type: 'reflection',
      state: 'available',
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    // Ramo A - Conexão
    {
      id: 'rel-conn-1',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Demonstrar interesse genuíno',
      description: 'Mostrar curiosidade real sobre a outra pessoa.',
      type: 'skill',
      state: 'locked',
      order: 1,
      branch: 'Ramo A — Conexão',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel-conn-2',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Escutar histórias sem corrigir',
      description: 'Permitir que o outro compartilhe sem interrupções ou correções.',
      type: 'experience',
      state: 'locked',
      order: 2,
      branch: 'Ramo A — Conexão',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel-conn-3',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Compartilhar algo pessoal',
      description: 'Abrir-se gradualmente, criando confiança mútua.',
      type: 'experience',
      state: 'locked',
      order: 3,
      branch: 'Ramo A — Conexão',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo B - Limites
    {
      id: 'rel-bound-1',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Identificar o que você quer',
      description: 'Clareza sobre seus próprios desejos e necessidades.',
      type: 'reflection',
      state: 'locked',
      order: 4,
      branch: 'Ramo B — Limites',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel-bound-2',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Aceitar um "não"',
      description: 'Respeitar a resposta do outro sem pressionar.',
      type: 'experience',
      state: 'locked',
      order: 5,
      branch: 'Ramo B — Limites',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel-bound-3',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Respeitar ritmos diferentes',
      description: 'Entender que cada pessoa tem seu próprio tempo.',
      type: 'skill',
      state: 'locked',
      order: 6,
      branch: 'Ramo B — Limites',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo C - Afeto
    {
      id: 'rel-aff-1',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Expressar carinho sem expectativa',
      description: 'Dar afeto sem esperar algo em troca.',
      type: 'experience',
      state: 'locked',
      order: 7,
      branch: 'Ramo C — Afeto',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel-aff-2',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Lidar com rejeição',
      description: 'Processar a rejeição sem se destruir.',
      type: 'reflection',
      state: 'locked',
      order: 8,
      branch: 'Ramo C — Afeto',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'rel-aff-3',
      guideId: 'relationships',
      parentNodeId: 'relationships-initial',
      title: 'Não transformar desejo em controle',
      description: 'Manter o desejo sem tentar controlar o outro.',
      type: 'reflection',
      state: 'locked',
      order: 9,
      branch: 'Ramo C — Afeto',
      createdAt: now,
      updatedAt: now,
    },

    // GUIA 3: Estabilidade Financeira
    {
      id: 'financial-initial',
      guideId: 'financial-stability',
      parentNodeId: null,
      title: 'Reconhecer sua realidade financeira',
      description: 'Ver a situação financeira sem julgamento moral.',
      type: 'reflection',
      state: 'available',
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    // Ramo A - Consciência
    {
      id: 'fin-cons-1',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Registrar gastos por curiosidade',
      description: 'Observar para onde o dinheiro vai, sem culpa.',
      type: 'experience',
      state: 'locked',
      order: 1,
      branch: 'Ramo A — Consciência',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'fin-cons-2',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Entender para onde o dinheiro vai',
      description: 'Mapear seus padrões de gasto.',
      type: 'skill',
      state: 'locked',
      order: 2,
      branch: 'Ramo A — Consciência',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'fin-cons-3',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Separar desejo de necessidade',
      description: 'Reconhecer a diferença entre o que você quer e o que precisa.',
      type: 'reflection',
      state: 'locked',
      order: 3,
      branch: 'Ramo A — Consciência',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo B - Estrutura
    {
      id: 'fin-struct-1',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Criar reserva mínima',
      description: 'Estabelecer uma pequena reserva de emergência.',
      type: 'experience',
      state: 'locked',
      order: 4,
      branch: 'Ramo B — Estrutura',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'fin-struct-2',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Reduzir um gasto recorrente',
      description: 'Identificar e reduzir um gasto que não é essencial.',
      type: 'experience',
      state: 'locked',
      order: 5,
      branch: 'Ramo B — Estrutura',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'fin-struct-3',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Planejar curto prazo',
      description: 'Fazer planos financeiros para o próximo mês.',
      type: 'skill',
      state: 'locked',
      order: 6,
      branch: 'Ramo B — Estrutura',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo C - Relação com dinheiro
    {
      id: 'fin-rel-1',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Identificar culpa ou medo financeiro',
      description: 'Reconhecer emoções relacionadas ao dinheiro.',
      type: 'reflection',
      state: 'locked',
      order: 7,
      branch: 'Ramo C — Relação com dinheiro',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'fin-rel-2',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Evitar comparação',
      description: 'Não se comparar financeiramente com outros.',
      type: 'reflection',
      state: 'locked',
      order: 8,
      branch: 'Ramo C — Relação com dinheiro',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'fin-rel-3',
      guideId: 'financial-stability',
      parentNodeId: 'financial-initial',
      title: 'Pensar dinheiro como meio, não identidade',
      description: 'Dinheiro é ferramenta, não define quem você é.',
      type: 'reflection',
      state: 'locked',
      order: 9,
      branch: 'Ramo C — Relação com dinheiro',
      createdAt: now,
      updatedAt: now,
    },

    // GUIA 4: O Caminho do Dao
    {
      id: 'dao-initial',
      guideId: 'dao-path',
      parentNodeId: null,
      title: 'Aceitar impermanência',
      description: 'Tudo muda. Nada permanece.',
      type: 'reflection',
      state: 'available',
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    // Ramo A - Wu Wei
    {
      id: 'dao-wuwei-1',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Observar antes de agir',
      description: 'Pausar e observar antes de reagir.',
      type: 'experience',
      state: 'locked',
      order: 1,
      branch: 'Ramo A — Wu Wei (Não-forçar)',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'dao-wuwei-2',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Reduzir excessos',
      description: 'Fazer menos, com mais presença.',
      type: 'experience',
      state: 'locked',
      order: 2,
      branch: 'Ramo A — Wu Wei (Não-forçar)',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'dao-wuwei-3',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Não reagir imediatamente',
      description: 'Dar espaço entre estímulo e resposta.',
      type: 'skill',
      state: 'locked',
      order: 3,
      branch: 'Ramo A — Wu Wei (Não-forçar)',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo B - Simplicidade
    {
      id: 'dao-simple-1',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Diminuir estímulos',
      description: 'Reduzir a quantidade de informações e distrações.',
      type: 'experience',
      state: 'locked',
      order: 4,
      branch: 'Ramo B — Simplicidade',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'dao-simple-2',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Valorizar o cotidiano',
      description: 'Encontrar beleza nas atividades simples do dia a dia.',
      type: 'reflection',
      state: 'locked',
      order: 5,
      branch: 'Ramo B — Simplicidade',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'dao-simple-3',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Fazer menos, com atenção',
      description: 'Priorizar qualidade sobre quantidade.',
      type: 'skill',
      state: 'locked',
      order: 6,
      branch: 'Ramo B — Simplicidade',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo C - Presença
    {
      id: 'dao-presence-1',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Estar inteiro em uma atividade',
      description: 'Fazer uma coisa de cada vez, com atenção total.',
      type: 'experience',
      state: 'locked',
      order: 7,
      branch: 'Ramo C — Presença',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'dao-presence-2',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Respirar conscientemente',
      description: 'Praticar respiração consciente como âncora.',
      type: 'experience',
      state: 'locked',
      order: 8,
      branch: 'Ramo C — Presença',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'dao-presence-3',
      guideId: 'dao-path',
      parentNodeId: 'dao-initial',
      title: 'Aceitar emoções sem lutar',
      description: 'Permitir que emoções existam sem tentar controlá-las.',
      type: 'reflection',
      state: 'locked',
      order: 9,
      branch: 'Ramo C — Presença',
      createdAt: now,
      updatedAt: now,
    },

    // GUIA 5: Criar Sentido
    {
      id: 'meaning-initial',
      guideId: 'creating-meaning',
      parentNodeId: null,
      title: 'Reconhecer o vazio',
      description: 'Aceitar que a vida não vem com sentido pré-fabricado.',
      type: 'reflection',
      state: 'available',
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
    // Ramo A - Criação
    {
      id: 'meaning-create-1',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Criar sem objetivo',
      description: 'Criar por criar, sem expectativa de resultado.',
      type: 'experience',
      state: 'locked',
      order: 1,
      branch: 'Ramo A — Criação',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'meaning-create-2',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Expressar algo pessoal',
      description: 'Colocar algo de si em uma criação.',
      type: 'experience',
      state: 'locked',
      order: 2,
      branch: 'Ramo A — Criação',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'meaning-create-3',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Aceitar imperfeição',
      description: 'Criar mesmo quando não está perfeito.',
      type: 'reflection',
      state: 'locked',
      order: 3,
      branch: 'Ramo A — Criação',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo B - Reflexão
    {
      id: 'meaning-reflect-1',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Escrever sobre si',
      description: 'Usar escrita como forma de autoconhecimento.',
      type: 'experience',
      state: 'locked',
      order: 4,
      branch: 'Ramo B — Reflexão',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'meaning-reflect-2',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Questionar valores herdados',
      description: 'Examinar crenças que você recebeu sem questionar.',
      type: 'reflection',
      state: 'locked',
      order: 5,
      branch: 'Ramo B — Reflexão',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'meaning-reflect-3',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Nomear o que importa',
      description: 'Identificar o que realmente tem significado para você.',
      type: 'reflection',
      state: 'locked',
      order: 6,
      branch: 'Ramo B — Reflexão',
      createdAt: now,
      updatedAt: now,
    },
    // Ramo C - Existência
    {
      id: 'meaning-exist-1',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Aceitar a falta de respostas',
      description: 'Viver com perguntas sem precisar de respostas definitivas.',
      type: 'reflection',
      state: 'locked',
      order: 7,
      branch: 'Ramo C — Existência',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'meaning-exist-2',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Viver o agora',
      description: 'Estar presente no momento atual, sem ficar preso ao passado ou futuro.',
      type: 'experience',
      state: 'locked',
      order: 8,
      branch: 'Ramo C — Existência',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'meaning-exist-3',
      guideId: 'creating-meaning',
      parentNodeId: 'meaning-initial',
      title: 'Não transformar a vida em projeto eterno',
      description: 'Viver a vida, não apenas planejá-la.',
      type: 'reflection',
      state: 'locked',
      order: 9,
      branch: 'Ramo C — Existência',
      createdAt: now,
      updatedAt: now,
    },
  ];

  // Garantir que todos os nós tenham ícones definidos
  // O ícone é parte dos dados do nó, não um nome mágico
  const nodes: GuideNode[] = nodesRaw.map(node => ({
    ...node,
    icon: node.icon || getDefaultIcons(node.type),
  }));

  return { guides, nodes };
}

