'use client';

import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'ko' | 'pt' | 'es' | 'ja' | 'de' | 'fr' | 'it' | 'zh-CN' | 'zh-TW';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string | string[];
  tString: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string | string[]>> = {
  en: {
    'footer.about': 'ABOUT',
    'footer.privacy': 'PRIVACY',
    'footer.terms': 'TERMS',
    'footer.language': 'LANGUAGE',
    'sections.habits': 'HABITS',
    'sections.journal': 'JOURNAL',
    'sections.finances': 'FINANCES',
    'sections.goals': 'GOALS',
    'sections.mapas': 'MAPS',
    'sections.biography': 'BIOGRAPHY',
    'sections.display': 'DISPLAY',
    'sections.feedback': 'FEEDBACK',
    'sections.guides': 'GUIDES',
    'about.title': 'ABOUT',
    'about.content1': 'Pixel Life is a gamified life management application that helps you organize and track your habits, goals, finances, and more.',
    'about.content2': 'With a pixelated and fun interface, we transform everyday tasks into an engaging and motivating experience.',
    'privacy.title': 'PRIVACY',
    'privacy.content1': 'Your privacy is important to us. This policy describes how we collect, use, and protect your personal information.',
    'privacy.data': 'Data Collected',
    'privacy.dataContent': 'We only collect information necessary to provide our services, including habit data, goals, and personalization preferences.',
    'privacy.use': 'Use of Data',
    'privacy.useContent': 'Your data is used exclusively to improve your experience in the application and is not shared with third parties.',
    'terms.title': 'TERMS',
    'terms.content1': 'By using Pixel Life, you agree to the following terms of use.',
    'terms.use': 'Use of Application',
    'terms.useContent': 'You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account.',
    'terms.liability': 'Limitation of Liability',
    'terms.liabilityContent': 'Pixel Life is provided "as is", without warranties of any kind, express or implied.',
    'display.myStats': 'MY STATS',
    'display.currentStreak': 'Current Streak',
    'display.longestStreak': 'Longest Streak',
    'display.trainings': 'Trainings',
    'display.daysRegistered': 'Days Registered',
    'display.goalsCompleted': 'Goals Completed',
    'display.skillsMastered': 'Skills Mastered',
    'display.activeHabits': 'Active Habits',
    'display.myProfile': 'MY PROFILE',
    'display.personalProfile': 'Personal Profile',
    'display.bio': 'Bio:',
    'display.characters': 'characters',
    'display.age': 'Age:',
    'display.city': 'City:',
    'display.title': 'Title:',
    'display.notInformed': 'Not informed',
    'display.availableMoney': 'Available Money',
    'display.remainingLimit': 'Remaining Limit',
    'display.reserve': 'Reserve',
    'display.showRemainingLimit': 'Show Available Limit',
    'display.showAvailableMoney': 'Show Money in Account',
    'display.selectStatus': 'Select Status',
    'display.changeStyle': 'Change Style',
    'display.viewHistory': 'View History',
    'display.achievements': 'Achievements',
    'display.enterCity': 'Enter your city',
    'display.titlePlaceholder': 'Ex: Developer, Student, etc.',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.remove': 'Remove',
    'common.add': 'Add',
    'common.addHabit': 'Add Habit',
    'common.newHabit': 'New Habit',
    'common.renameHabit': 'Rename Habit',
    'common.habitName': 'Habit name:',
    'common.newHabitName': 'New habit name:',
    'common.addEntry': 'Add Entry',
    'common.saving': 'Saving...',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.of': 'of',
    'common.selectDate': 'Select Date',
    'common.description': 'Description',
    'common.value': 'Value',
    'common.date': 'Date',
    'common.category': 'Category',
    'common.type': 'Type',
    'common.expense': 'Expense',
    'common.income': 'Income',
    'common.removeConfirm': 'Remove',
    'common.deleteConfirm': 'Are you sure you want to delete this?',
    'common.confirmAction': 'Confirm action',
    'common.addExpenseIncome': 'Add Expense/Income',
    'common.editQuickThought': 'Edit quick thought',
    'common.writeQuickThought': 'Write a quick thought',
    'common.descriptionPlaceholder': 'Ex: Material purchase',
    'common.expenseIncome': 'Expense/Income',
    'common.gasto': 'Expense',
    'common.ganho': 'Income',
    'journal.writeAboutDay': 'Write about your day...',
    'journal.quickThoughts': 'QUICK THOUGHTS',
    'journal.longText': 'Long Text',
    'journal.addQuickThought': '+ Add quick thought',
    'journal.noThoughtsThisMonth': 'No thoughts this month',
    'journal.moodGood': 'Good',
    'journal.moodNeutral': 'Neutral',
    'journal.moodBad': 'Bad',
    'journal.days': ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    'journal.daysShort': ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    'journal.months': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    'journal.monthsFull': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    'journal.clickToAdd': 'Click to add',
    'goals.type': 'Type',
    'goals.typeHouse': 'House',
    'goals.typeVehicle': 'Vehicle',
    'goals.typeInvestment': 'Investment',
    'goals.typeEducation': 'Education',
    'goals.typeCustom': 'Custom',
    'goals.statusCompleted': 'Completed',
    'goals.statusInProgress': 'In Progress',
    'goals.statusLocked': 'Locked',
    'goals.statusPaused': 'Paused',
    'goals.orderBy': 'Order by',
    'goals.orderByValue': 'Value',
    'goals.orderByStatus': 'Status',
    'goals.orderByDate': 'Date',
    'goals.orderAsc': 'ascending',
    'goals.orderDesc': 'descending',
    'mapas.categories': 'Categories',
    'mapas.items': 'Items',
    'mapas.progress': 'Progress',
    'biography.title': 'Biography',
    'biography.addEvent': 'Add Event',
    'biography.timeline': 'Timeline',
    'biography.dossiers': 'Dossiers',
    'biography.aboutMe': 'About Me',
    'biography.noEventsYet': 'No events yet. Start recording your story!',
    'finances.daily': 'Daily',
    'finances.monthly': 'Monthly',
    'finances.reserve': 'Reserve',
    'finances.monthlyLimit': 'Monthly Limit',
    'finances.accumulatedSpending': 'Accumulated Spending',
    'finances.available': 'Available',
    'finances.recommendedDaily': 'Recommended Daily',
    'finances.statusBelowPace': 'Below pace',
    'finances.statusAttention': 'Attention',
    'finances.statusAboveLimit': 'Above limit',
    'finances.utilized': 'utilized',
    'finances.resetDay': 'Reset day',
    'finances.currentAccountMoney': 'Current money in account',
    'finances.day': 'Day',
    'finances.details': 'Details',
    'finances.dailyTotal': 'Daily Total',
    'finances.remainingLimit': 'Limite',
    'finances.accountMoney': 'Money in Account',
    'finances.noEntriesRegistered': 'No entries registered',
    'finances.addMovement': 'Add Movement',
    'finances.totalReserve': 'Total Reserve',
    'finances.resetDayMustBe': 'Reset day must be between 1 and 31.',
    'goals.possessionsAndGoals': 'Possessions and Goals',
    'goals.newGoal': 'New Goal',
    'goals.targetValue': 'Target Value (R$)',
    'goals.completed': 'Completed',
    'goals.icon': 'Icon:',
    'goals.descriptionPlaceholder': 'Ex: Dream house',
    'goals.create': 'Create',
    'goals.current': 'Current',
    'goals.target': 'Target',
    'goals.accumulatedValue': 'Accumulated value in possessions:',
    'common.history': 'History',
    'common.hide': 'Hide',
    'common.deposit': 'Deposit',
    'common.withdrawal': 'Withdrawal',
    'common.status': 'Status:',
    'guides.title': 'Guides — Possible Paths',
    'guides.subtitle': 'There is no "right life". There are possible paths. Choose what to explore.',
    'guides.officialGuides': 'Official Guides',
    'guides.loading': 'Loading official guides... If you are a new user, guides will be initialized shortly.',
    'guides.myGuides': 'My Guides',
    'guides.createGuide': '+ Create Guide',
    'guides.noCustomGuides': 'You haven\'t created any custom guides yet.',
    'guides.back': '← Back',
    'guides.createCustomGuide': 'Create Custom Guide',
    'guides.pathName': 'Path Name',
    'guides.pathNamePlaceholder': 'Ex: My Life Project',
    'guides.description': 'Description',
    'guides.descriptionPlaceholder': 'Describe this path...',
    'guides.philosophicalNote': 'Philosophical Note (optional)',
    'guides.philosophicalNotePlaceholder': 'A short reflection on this path...',
    'guides.fillNameDescription': 'Fill in name and description',
    'guides.nodeStateLocked': 'Locked',
    'guides.nodeStateAvailable': 'Available',
    'guides.nodeStateInProgress': 'In Progress',
    'guides.nodeStateIntegrated': 'Integrated',
    'guides.nodeStateAbandoned': 'Abandoned',
    'guides.nodeTypeSkill': 'Skill',
    'guides.nodeTypeExperience': 'Experience',
    'guides.nodeTypeHabit': 'Habit',
    'guides.nodeTypeChallenge': 'Challenge',
    'guides.nodeTypeReflection': 'Reflection',
    'guides.nodeTypeKnowledge': 'Knowledge',
    'common.editGoal': 'Edit Goal',
    'common.editAccountMoney': 'Edit Account Money',
    'common.editEntry': 'Edit Entry',
    'common.editCategory': 'Edit Category',
    'common.editItem': 'Edit Item',
    'common.editList': 'Edit List',
    'common.newCategory': 'New Category',
    'common.newItem': 'New Item',
    'common.newList': 'New Future List',
    'common.addStory': 'Add Story',
    'common.clickToEdit': 'Click to edit',
    'bio.noBioYet': 'No bio yet. Click "Edit" to add one.',
  },
  ko: {
    'footer.about': '소개',
    'footer.privacy': '개인정보',
    'footer.terms': '이용약관',
    'footer.language': '언어',
    'sections.habits': '습관',
    'sections.journal': '일기',
    'sections.finances': '재정',
    'sections.goals': '목표',
    'sections.mapas': '지도',
    'sections.biography': '전기',
    'sections.display': '표시',
    'sections.feedback': '피드백',
    'sections.guides': '가이드',
    'about.title': '소개',
    'about.content1': 'Pixel Life는 습관, 목표, 재정 등을 정리하고 추적하는 데 도움이 되는 게임화된 생활 관리 애플리케이션입니다.',
    'about.content2': '픽셀화되고 재미있는 인터페이스로 일상적인 작업을 매력적이고 동기부여가 되는 경험으로 전환합니다.',
    'privacy.title': '개인정보',
    'privacy.content1': '귀하의 개인정보는 저희에게 중요합니다. 이 정책은 개인정보를 수집, 사용 및 보호하는 방법을 설명합니다.',
    'privacy.data': '수집된 데이터',
    'privacy.dataContent': '저희는 습관 데이터, 목표 및 개인화 기본 설정을 포함하여 서비스를 제공하는 데 필요한 정보만 수집합니다.',
    'privacy.use': '데이터 사용',
    'privacy.useContent': '귀하의 데이터는 애플리케이션 내 경험을 개선하는 데 독점적으로 사용되며 제3자와 공유되지 않습니다.',
    'terms.title': '이용약관',
    'terms.content1': 'Pixel Life를 사용하면 다음 이용약관에 동의하는 것입니다.',
    'terms.use': '애플리케이션 사용',
    'terms.useContent': '귀하는 계정의 기밀성을 유지하고 귀하의 계정에서 발생하는 모든 활동에 대한 책임이 있습니다.',
    'terms.liability': '책임 제한',
    'terms.liabilityContent': 'Pixel Life는 명시적이거나 묵시적인 어떠한 종류의 보증 없이 "있는 그대로" 제공됩니다.',
    'display.myStats': '내 통계',
    'display.currentStreak': '현재 연속',
    'display.longestStreak': '최장 연속',
    'display.trainings': '훈련',
    'display.daysRegistered': '등록된 일수',
    'display.goalsCompleted': '완료된 목표',
    'display.skillsMastered': '숙련된 기술',
    'display.activeHabits': '활성 습관',
    'display.myProfile': '내 프로필',
    'display.personalProfile': '개인 프로필',
    'display.bio': '소개:',
    'display.characters': '자',
    'display.age': '나이:',
    'display.city': '도시:',
    'display.title': '직함:',
    'display.notInformed': '정보 없음',
    'display.availableMoney': '사용 가능한 돈',
    'display.remainingLimit': '남은 한도',
    'display.reserve': '예비금',
    'display.showRemainingLimit': '남은 한도 표시',
    'display.showAvailableMoney': '사용 가능한 돈 표시',
    'display.selectStatus': '상태 선택',
    'display.changeStyle': '스타일 변경',
    'display.viewHistory': '기록 보기',
    'display.achievements': '성취',
    'display.enterCity': '도시를 입력하세요',
    'display.titlePlaceholder': '예: 개발자, 학생 등',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.edit': '편집',
    'common.delete': '삭제',
    'common.remove': '제거',
    'common.add': '추가',
    'common.addHabit': '습관 추가',
    'common.newHabit': '새 습관',
    'common.renameHabit': '습관 이름 변경',
    'common.habitName': '습관 이름:',
    'common.newHabitName': '새 습관 이름:',
    'common.addEntry': '항목 추가',
    'common.saving': '저장 중...',
    'common.confirm': '확인',
    'common.close': '닫기',
    'common.yes': '예',
    'common.no': '아니오',
    'common.of': '의',
    'common.selectDate': '날짜 선택',
    'common.description': '설명',
    'common.value': '값',
    'common.date': '날짜',
    'common.category': '카테고리',
    'common.type': '유형',
    'common.expense': '지출',
    'common.income': '수입',
    'common.removeConfirm': '제거',
    'common.deleteConfirm': '정말로 삭제하시겠습니까?',
    'common.confirmAction': '작업 확인',
    'common.addExpenseIncome': '지출/수입 추가',
    'common.editQuickThought': '빠른 생각 편집',
    'common.writeQuickThought': '빠른 생각 작성',
    'common.descriptionPlaceholder': '예: 재료 구매',
    'common.expenseIncome': '지출/수입',
    'common.gasto': '지출',
    'common.ganho': '수입',
    'journal.writeAboutDay': '오늘 하루에 대해 작성하세요...',
    'journal.quickThoughts': '빠른 생각',
    'journal.longText': '긴 텍스트',
    'journal.addQuickThought': '+ 빠른 생각 추가',
    'journal.noThoughtsThisMonth': '이번 달에는 생각이 없습니다',
    'journal.moodGood': '좋음',
    'journal.moodNeutral': '보통',
    'journal.moodBad': '나쁨',
    'journal.days': ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],
    'journal.daysShort': ['일', '월', '화', '수', '목', '금', '토'],
    'journal.months': ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    'journal.monthsFull': ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월'],
    'journal.clickToAdd': '추가하려면 클릭',
    'goals.type': '유형',
    'goals.typeHouse': '집',
    'goals.typeVehicle': '차량',
    'goals.typeInvestment': '투자',
    'goals.typeEducation': '교육',
    'goals.typeCustom': '사용자 정의',
    'goals.statusCompleted': '완료',
    'goals.statusInProgress': '진행 중',
    'goals.statusLocked': '잠김',
    'goals.orderBy': '정렬 기준',
    'goals.orderByValue': '값',
    'goals.orderByStatus': '상태',
    'goals.orderByDate': '날짜',
    'goals.orderAsc': '오름차순',
    'goals.orderDesc': '내림차순',
    'mapas.categories': '카테고리',
    'mapas.items': '항목',
    'mapas.progress': '진행 상황',
    'biography.title': '전기',
    'biography.addEvent': '이벤트 추가',
    'biography.timeline': '타임라인',
    'biography.dossiers': '파일',
    'biography.aboutMe': '나에 대해',
    'biography.noEventsYet': '아직 이벤트가 없습니다. 이야기를 기록하기 시작하세요!',
    'finances.daily': '일일',
    'finances.monthly': '월간',
    'finances.reserve': '예비금',
    'finances.monthlyLimit': '월 한도',
    'finances.accumulatedSpending': '누적 지출',
    'finances.available': '사용 가능',
    'finances.recommendedDaily': '권장 일일',
    'finances.statusBelowPace': '속도 미달',
    'finances.statusAttention': '주의',
    'finances.statusAboveLimit': '한도 초과',
    'finances.utilized': '사용됨',
    'finances.resetDay': '재설정일',
    'finances.currentAccountMoney': '계정의 현재 금액',
    'finances.day': '일',
    'finances.details': '세부사항',
    'finances.dailyTotal': '일일 합계',
    'finances.remainingLimit': '남은 한도',
    'finances.accountMoney': '계정 금액',
    'finances.noEntriesRegistered': '등록된 항목 없음',
    'finances.addMovement': '거래 추가',
    'finances.totalReserve': '총 예비금',
    'finances.resetDayMustBe': '재설정일은 1일부터 31일 사이여야 합니다.',
    'goals.possessionsAndGoals': '소유물 및 목표',
    'goals.newGoal': '새 목표',
    'goals.targetValue': '목표 가치 (R$)',
    'goals.completed': '완료됨',
    'goals.icon': '아이콘:',
    'goals.descriptionPlaceholder': '예: 꿈의 집',
    'goals.create': '생성',
    'goals.current': '현재',
    'goals.target': '목표',
    'goals.accumulatedValue': '보유 자산의 누적 가치:',
    'common.history': '기록',
    'common.hide': '숨기기',
    'common.deposit': '입금',
    'common.withdrawal': '출금',
    'common.status': '상태:',
    'guides.title': '가이드 — 가능한 경로',
    'guides.subtitle': '"올바른 삶"은 없습니다. 가능한 경로가 있습니다. 탐색할 것을 선택하세요.',
    'guides.officialGuides': '공식 가이드',
    'guides.loading': '공식 가이드를 로드하는 중... 새 사용자인 경우 가이드가 곧 초기화됩니다.',
    'guides.myGuides': '내 가이드',
    'guides.createGuide': '+ 가이드 만들기',
    'guides.noCustomGuides': '아직 사용자 정의 가이드를 만들지 않았습니다.',
    'guides.back': '← 뒤로',
    'guides.createCustomGuide': '사용자 정의 가이드 만들기',
    'guides.pathName': '경로 이름',
    'guides.pathNamePlaceholder': '예: 내 인생 프로젝트',
    'guides.description': '설명',
    'guides.descriptionPlaceholder': '이 경로를 설명하세요...',
    'guides.philosophicalNote': '철학적 노트 (선택사항)',
    'guides.philosophicalNotePlaceholder': '이 경로에 대한 짧은 성찰...',
    'guides.fillNameDescription': '이름과 설명을 입력하세요',
    'guides.nodeStateLocked': '잠김',
    'guides.nodeStateAvailable': '사용 가능',
    'guides.nodeStateInProgress': '진행 중',
    'guides.nodeStateIntegrated': '통합됨',
    'guides.nodeStateAbandoned': '포기됨',
    'guides.nodeTypeSkill': '기술',
    'guides.nodeTypeExperience': '경험',
    'guides.nodeTypeHabit': '습관',
    'guides.nodeTypeChallenge': '도전',
    'guides.nodeTypeReflection': '성찰',
    'guides.nodeTypeKnowledge': '지식',
    'common.editGoal': '목표 편집',
    'common.editAccountMoney': '계정 금액 편집',
    'common.editEntry': '항목 편집',
    'common.editCategory': '카테고리 편집',
    'common.editItem': '항목 편집',
    'common.editList': '목록 편집',
    'common.newCategory': '새 카테고리',
    'common.newItem': '새 항목',
    'common.newList': '새 미래 목록',
    'common.addStory': '이야기 추가',
    'common.clickToEdit': '편집하려면 클릭',
    'bio.noBioYet': '아직 소개가 없습니다. "편집"을 클릭하여 추가하세요.',
  },
  pt: {
    'footer.about': 'SOBRE',
    'footer.privacy': 'PRIVACIDADE',
    'footer.terms': 'TERMOS',
    'footer.language': 'IDIOMA',
    'sections.habits': 'HÁBITOS',
    'sections.journal': 'DIÁRIO',
    'sections.finances': 'FINANÇAS',
    'sections.goals': 'OBJETIVOS',
    'sections.mapas': 'MAPAS',
    'sections.biography': 'BIOGRAFIA',
    'sections.display': 'DISPLAY',
    'sections.feedback': 'FEEDBACK',
    'sections.guides': 'GUIAS',
    'about.title': 'SOBRE',
    'about.content1': 'Pixel Life é uma aplicação de gerenciamento de vida gamificada que ajuda você a organizar e acompanhar seus hábitos, objetivos, finanças e muito mais.',
    'about.content2': 'Com uma interface pixelada e divertida, transformamos tarefas do dia a dia em uma experiência envolvente e motivadora.',
    'privacy.title': 'PRIVACIDADE',
    'privacy.content1': 'Sua privacidade é importante para nós. Esta política descreve como coletamos, usamos e protegemos suas informações pessoais.',
    'privacy.data': 'Dados Coletados',
    'privacy.dataContent': 'Coletamos apenas as informações necessárias para fornecer nossos serviços, incluindo dados de hábitos, objetivos e preferências de personalização.',
    'privacy.use': 'Uso dos Dados',
    'privacy.useContent': 'Seus dados são usados exclusivamente para melhorar sua experiência na aplicação e não são compartilhados com terceiros.',
    'terms.title': 'TERMOS',
    'terms.content1': 'Ao usar o Pixel Life, você concorda com os seguintes termos de uso.',
    'terms.use': 'Uso da Aplicação',
    'terms.useContent': 'Você é responsável por manter a confidencialidade de sua conta e por todas as atividades que ocorrem sob sua conta.',
    'terms.liability': 'Limitação de Responsabilidade',
    'terms.liabilityContent': 'O Pixel Life é fornecido "como está", sem garantias de qualquer tipo, expressas ou implícitas.',
    'display.myStats': 'MINHAS ESTATÍSTICAS',
    'display.currentStreak': 'Sequência Atual',
    'display.longestStreak': 'Maior Sequência',
    'display.trainings': 'Treinos',
    'display.daysRegistered': 'Dias Registrados',
    'display.goalsCompleted': 'Objetivos Completados',
    'display.skillsMastered': 'Habilidades Dominadas',
    'display.activeHabits': 'Hábitos Ativos',
    'display.myProfile': 'MEU PERFIL',
    'display.personalProfile': 'Perfil Pessoal',
    'display.bio': 'Bio:',
    'display.characters': 'caracteres',
    'display.age': 'Idade:',
    'display.city': 'Cidade:',
    'display.title': 'Título:',
    'display.notInformed': 'Não informado',
    'display.availableMoney': 'Em conta',
    'display.remainingLimit': 'Disponível',
    'display.reserve': 'Reserva',
    'display.showRemainingLimit': 'Mostrar Limite Disponível',
    'display.showAvailableMoney': 'Mostrar Dinheiro em Conta',
    'display.selectStatus': 'Selecione os Status',
    'display.changeStyle': 'Mudar Estilo',
    'display.viewHistory': 'Ver Histórico',
    'display.achievements': 'Conquistas',
    'display.enterCity': 'Digite sua cidade',
    'display.titlePlaceholder': 'Ex: Desenvolvedor, Estudante, etc.',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.remove': 'Remover',
    'common.add': 'Adicionar',
    'common.addHabit': 'Adicionar Hábito',
    'common.newHabit': 'Novo hábito',
    'common.renameHabit': 'Renomear hábito',
    'common.habitName': 'Nome do hábito:',
    'common.newHabitName': 'Novo nome do hábito:',
    'common.addEntry': 'Adicionar Entrada',
    'common.saving': 'Salvando...',
    'common.confirm': 'Confirmar',
    'common.close': 'Fechar',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.of': 'de',
    'common.selectDate': 'Selecionar Data',
    'common.description': 'Descrição',
    'common.value': 'Valor',
    'common.date': 'Data',
    'common.category': 'Categoria',
    'common.type': 'Tipo',
    'common.expense': 'Gasto',
    'common.income': 'Ganho',
    'common.removeConfirm': 'Remover',
    'common.deleteConfirm': 'Tem certeza que deseja excluir?',
    'common.confirmAction': 'Confirmar ação',
    'common.addExpenseIncome': 'Adicionar Gasto/Ganho',
    'common.editQuickThought': 'Editar pensamento rápido',
    'common.writeQuickThought': 'Escreva um pensamento rápido',
    'common.descriptionPlaceholder': 'Ex: Compra de material',
    'common.expenseIncome': 'Gasto/Ganho',
    'common.gasto': 'Gasto',
    'common.ganho': 'Ganho',
    'journal.writeAboutDay': 'Escreva sobre seu dia...',
    'journal.quickThoughts': 'PENSAMENTOS RÁPIDOS',
    'journal.longText': 'Texto Longo',
    'journal.addQuickThought': '+ Adicionar pensamento rápido',
    'journal.noThoughtsThisMonth': 'Nenhum pensamento registrado neste mês',
    'journal.moodGood': 'Bom',
    'journal.moodNeutral': 'Médio',
    'journal.moodBad': 'Ruim',
    'journal.days': ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    'journal.daysShort': ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    'journal.months': ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
    'journal.monthsFull': ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    'journal.clickToAdd': 'Clique para adicionar',
    'goals.type': 'Tipo',
    'goals.typeHouse': 'Casa',
    'goals.typeVehicle': 'Veículo',
    'goals.typeInvestment': 'Investimento',
    'goals.typeEducation': 'Educação',
    'goals.typeCustom': 'Personalizado',
    'goals.statusCompleted': 'Quitado',
    'goals.statusInProgress': 'Em progresso',
    'goals.statusLocked': 'Bloqueado',
    'goals.statusPaused': 'Pausado',
    'goals.orderBy': 'Ordenar por',
    'goals.orderByValue': 'Valor',
    'goals.orderByStatus': 'Status',
    'goals.orderByDate': 'Data',
    'goals.orderAsc': 'crescente',
    'goals.orderDesc': 'decrescente',
    'mapas.categories': 'Categorias',
    'mapas.items': 'Itens',
    'mapas.progress': 'Progresso',
    'biography.title': 'Biografia',
    'biography.addEvent': 'Adicionar Evento',
    'biography.timeline': 'Linha do Tempo',
    'biography.dossiers': 'Dossiês',
    'biography.aboutMe': 'Sobre mim',
    'biography.noEventsYet': 'Nenhum evento ainda. Comece a registrar sua história!',
    'finances.daily': 'Diário',
    'finances.monthly': 'Mensal',
    'finances.reserve': 'Reserva',
    'finances.monthlyLimit': 'Limite Mensal',
    'finances.accumulatedSpending': 'Gasto Acumulado',
    'finances.available': 'Disponível',
    'finances.recommendedDaily': 'Diário Recomendado',
    'finances.statusBelowPace': 'Abaixo do ritmo',
    'finances.statusAttention': 'Atenção',
    'finances.statusAboveLimit': 'Acima do limite',
    'finances.utilized': 'utilizado',
    'finances.resetDay': 'Dia de reset',
    'finances.currentAccountMoney': 'Dinheiro atual em conta',
    'finances.day': 'Dia',
    'finances.details': 'Detalhes',
    'finances.dailyTotal': 'Total diário',
    'finances.remainingLimit': 'Limite',
    'finances.accountMoney': 'Em conta',
    'finances.noEntriesRegistered': 'Nenhuma entrada registrada',
    'finances.addMovement': 'Adicionar Movimentação',
    'finances.totalReserve': 'Total da Reserva',
    'finances.resetDayMustBe': 'Dia de reset deve estar entre 1 e 31.',
    'goals.possessionsAndGoals': 'Posses e Objetivos',
    'goals.newGoal': 'Novo Objetivo',
    'goals.targetValue': 'Valor Alvo (R$)',
    'goals.completed': 'Quitado',
    'goals.icon': 'Ícone:',
    'goals.descriptionPlaceholder': 'Ex: Casa dos sonhos',
    'goals.create': 'Criar',
    'goals.current': 'Atual',
    'goals.target': 'Meta',
    'goals.accumulatedValue': 'Valor em posses:',
    'common.history': 'Histórico',
    'common.hide': 'Ocultar',
    'common.deposit': 'Depósito',
    'common.withdrawal': 'Retirada',
    'common.status': 'Status:',
    'guides.title': 'Guias — Caminhos Possíveis',
    'guides.subtitle': 'Não existe "vida certa". Existem caminhos possíveis. Escolha o que explorar.',
    'guides.officialGuides': 'Guias Oficiais',
    'guides.loading': 'Carregando guias oficiais... Se você é um novo usuário, os guias serão inicializados em breve.',
    'guides.myGuides': 'Meus Guias',
    'guides.createGuide': '+ Criar Guia',
    'guides.noCustomGuides': 'Você ainda não criou nenhum guia customizado.',
    'guides.back': '← Voltar',
    'guides.createCustomGuide': 'Criar Guia Customizado',
    'guides.pathName': 'Nome do Caminho',
    'guides.pathNamePlaceholder': 'Ex: Meu Projeto de Vida',
    'guides.description': 'Descrição',
    'guides.descriptionPlaceholder': 'Descreva este caminho...',
    'guides.philosophicalNote': 'Nota Filosófica (opcional)',
    'guides.philosophicalNotePlaceholder': 'Uma reflexão curta sobre este caminho...',
    'guides.fillNameDescription': 'Preencha nome e descrição',
    'guides.nodeStateLocked': 'Bloqueado',
    'guides.nodeStateAvailable': 'Disponível',
    'guides.nodeStateInProgress': 'Em Progresso',
    'guides.nodeStateIntegrated': 'Integrado',
    'guides.nodeStateAbandoned': 'Abandonado',
    'guides.nodeTypeSkill': 'Habilidade',
    'guides.nodeTypeExperience': 'Experiência',
    'guides.nodeTypeHabit': 'Hábito',
    'guides.nodeTypeChallenge': 'Desafio',
    'guides.nodeTypeReflection': 'Reflexão',
    'guides.nodeTypeKnowledge': 'Conhecimento',
    'common.editGoal': 'Editar Objetivo',
    'common.editAccountMoney': 'Editar Dinheiro em Conta',
    'common.editEntry': 'Editar Entrada',
    'common.editCategory': 'Editar Categoria',
    'common.editItem': 'Editar Item',
    'common.editList': 'Editar Lista',
    'common.newCategory': 'Nova Categoria',
    'common.newItem': 'Novo Item',
    'common.newList': 'Nova Lista Futura',
    'common.addStory': 'Adicionar História',
    'common.clickToEdit': 'Clique para editar',
    'bio.noBioYet': 'Nenhuma bio ainda. Clique em "Editar" para adicionar uma.',
  },
  es: {
    'footer.about': 'ACERCA DE',
    'footer.privacy': 'PRIVACIDAD',
    'footer.terms': 'TÉRMINOS',
    'footer.language': 'IDIOMA',
    'sections.habits': 'HÁBITOS',
    'sections.journal': 'DIARIO',
    'sections.finances': 'FINANZAS',
    'sections.goals': 'OBJETIVOS',
    'sections.mapas': 'MAPAS',
    'sections.biography': 'BIOGRAFÍA',
    'sections.display': 'MOSTRAR',
    'sections.feedback': 'RETROALIMENTACIÓN',
    'sections.guides': 'GUÍAS',
    'about.title': 'ACERCA DE',
    'about.content1': 'Pixel Life es una aplicación de gestión de vida gamificada que te ayuda a organizar y rastrear tus hábitos, objetivos, finanzas y más.',
    'about.content2': 'Con una interfaz pixelada y divertida, transformamos las tareas cotidianas en una experiencia atractiva y motivadora.',
    'privacy.title': 'PRIVACIDAD',
    'privacy.content1': 'Tu privacidad es importante para nosotros. Esta política describe cómo recopilamos, usamos y protegemos tu información personal.',
    'privacy.data': 'Datos Recopilados',
    'privacy.dataContent': 'Solo recopilamos la información necesaria para brindar nuestros servicios, incluidos datos de hábitos, objetivos y preferencias de personalización.',
    'privacy.use': 'Uso de Datos',
    'privacy.useContent': 'Tus datos se usan exclusivamente para mejorar tu experiencia en la aplicación y no se comparten con terceros.',
    'terms.title': 'TÉRMINOS',
    'terms.content1': 'Al usar Pixel Life, aceptas los siguientes términos de uso.',
    'terms.use': 'Uso de la Aplicación',
    'terms.useContent': 'Eres responsable de mantener la confidencialidad de tu cuenta y de todas las actividades que ocurran bajo tu cuenta.',
    'terms.liability': 'Limitación de Responsabilidad',
    'terms.liabilityContent': 'Pixel Life se proporciona "tal cual", sin garantías de ningún tipo, expresas o implícitas.',
    'display.myStats': 'MIS ESTADÍSTICAS',
    'display.currentStreak': 'Racha Actual',
    'display.longestStreak': 'Racha Más Larga',
    'display.trainings': 'Entrenamientos',
    'display.daysRegistered': 'Días Registrados',
    'display.goalsCompleted': 'Objetivos Completados',
    'display.skillsMastered': 'Habilidades Dominadas',
    'display.activeHabits': 'Hábitos Activos',
    'display.myProfile': 'MI PERFIL',
    'display.personalProfile': 'Perfil Personal',
    'display.bio': 'Bio:',
    'display.characters': 'caracteres',
    'display.age': 'Edad:',
    'display.city': 'Ciudad:',
    'display.title': 'Título:',
    'display.notInformed': 'No informado',
    'display.availableMoney': 'Dinero Disponible',
    'display.remainingLimit': 'Límite Restante',
    'display.reserve': 'Reserva',
    'display.showRemainingLimit': 'Mostrar Límite Restante',
    'display.showAvailableMoney': 'Mostrar Dinero Disponible',
    'display.selectStatus': 'Seleccionar Estado',
    'display.changeStyle': 'Cambiar Estilo',
    'display.viewHistory': 'Ver Historial',
    'display.achievements': 'Logros',
    'display.enterCity': 'Ingresa tu ciudad',
    'display.titlePlaceholder': 'Ej: Desarrollador, Estudiante, etc.',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.remove': 'Remover',
    'common.add': 'Agregar',
    'common.addHabit': 'Agregar Hábito',
    'common.newHabit': 'Nuevo hábito',
    'common.renameHabit': 'Renombrar hábito',
    'common.habitName': 'Nombre del hábito:',
    'common.newHabitName': 'Nuevo nombre del hábito:',
    'common.addEntry': 'Agregar Entrada',
    'common.saving': 'Guardando...',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.of': 'de',
    'common.selectDate': 'Seleccionar Fecha',
    'common.description': 'Descripción',
    'common.value': 'Valor',
    'common.date': 'Fecha',
    'common.category': 'Categoría',
    'common.type': 'Tipo',
    'common.expense': 'Gasto',
    'common.income': 'Ingreso',
    'common.removeConfirm': 'Remover',
    'common.deleteConfirm': '¿Estás seguro de que deseas eliminar esto?',
    'common.confirmAction': 'Confirmar acción',
    'common.addExpenseIncome': 'Agregar Gasto/Ingreso',
    'common.editQuickThought': 'Editar pensamiento rápido',
    'common.writeQuickThought': 'Escribe un pensamiento rápido',
    'common.descriptionPlaceholder': 'Ej: Compra de material',
    'common.expenseIncome': 'Gasto/Ingreso',
    'common.gasto': 'Gasto',
    'common.ganho': 'Ingreso',
    'journal.writeAboutDay': 'Escribe sobre tu día...',
    'journal.quickThoughts': 'PENSAMIENTOS RÁPIDOS',
    'journal.longText': 'Texto Largo',
    'journal.addQuickThought': '+ Agregar pensamiento rápido',
    'journal.noThoughtsThisMonth': 'Ningún pensamiento registrado este mes',
    'journal.moodGood': 'Bueno',
    'journal.moodNeutral': 'Neutral',
    'journal.moodBad': 'Malo',
    'journal.days': ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
    'journal.daysShort': ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'],
    'journal.months': ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
    'journal.monthsFull': ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
    'journal.clickToAdd': 'Haz clic para agregar',
    'goals.type': 'Tipo',
    'goals.typeHouse': 'Casa',
    'goals.typeVehicle': 'Vehículo',
    'goals.typeInvestment': 'Inversión',
    'goals.typeEducation': 'Educación',
    'goals.typeCustom': 'Personalizado',
    'goals.statusCompleted': 'Completado',
    'goals.statusInProgress': 'En Progreso',
    'goals.statusLocked': 'Bloqueado',
    'goals.statusPaused': 'Pausado',
    'goals.orderBy': 'Ordenar por',
    'goals.orderByValue': 'Valor',
    'goals.orderByStatus': 'Estado',
    'goals.orderByDate': 'Fecha',
    'goals.orderAsc': 'ascendente',
    'goals.orderDesc': 'descendente',
    'mapas.categories': 'Categorías',
    'mapas.items': 'Elementos',
    'mapas.progress': 'Progreso',
    'biography.title': 'Biografía',
    'biography.addEvent': 'Agregar Evento',
    'biography.timeline': 'Línea de Tiempo',
    'biography.dossiers': 'Dossiers',
    'biography.aboutMe': 'Sobre Mí',
    'biography.noEventsYet': 'Aún no hay eventos. ¡Comienza a registrar tu historia!',
    'finances.daily': 'Diario',
    'finances.monthly': 'Mensual',
    'finances.reserve': 'Reserva',
    'finances.monthlyLimit': 'Límite Mensual',
    'finances.accumulatedSpending': 'Gasto Acumulado',
    'finances.available': 'Disponible',
    'finances.recommendedDaily': 'Diario Recomendado',
    'finances.statusBelowPace': 'Por debajo del ritmo',
    'finances.statusAttention': 'Atención',
    'finances.statusAboveLimit': 'Por encima del límite',
    'finances.utilized': 'utilizado',
    'finances.resetDay': 'Día de reinicio',
    'finances.currentAccountMoney': 'Dinero actual en cuenta',
    'finances.day': 'Día',
    'finances.details': 'Detalles',
    'finances.dailyTotal': 'Total Diario',
    'finances.remainingLimit': 'Límite Restante',
    'finances.accountMoney': 'Dinero en Cuenta',
    'finances.noEntriesRegistered': 'No hay entradas registradas',
    'finances.addMovement': 'Agregar Movimiento',
    'finances.totalReserve': 'Total de la Reserva',
    'finances.resetDayMustBe': 'El día de reinicio debe estar entre 1 y 31.',
    'goals.possessionsAndGoals': 'Posesiones y Objetivos',
    'goals.newGoal': 'Nuevo Objetivo',
    'goals.targetValue': 'Valor Objetivo (R$)',
    'goals.completed': 'Completado',
    'goals.icon': 'Ícono:',
    'goals.descriptionPlaceholder': 'Ej: Casa de los sueños',
    'goals.create': 'Crear',
    'goals.current': 'Actual',
    'goals.target': 'Objetivo',
    'goals.accumulatedValue': 'Valor acumulado en posesiones:',
    'common.history': 'Historial',
    'common.hide': 'Ocultar',
    'common.deposit': 'Depósito',
    'common.withdrawal': 'Retiro',
    'common.status': 'Estado:',
    'guides.title': 'Guías — Caminos Posibles',
    'guides.subtitle': 'No existe una "vida correcta". Existen caminos posibles. Elige qué explorar.',
    'guides.officialGuides': 'Guías Oficiales',
    'guides.loading': 'Cargando guías oficiales... Si eres un nuevo usuario, las guías se inicializarán pronto.',
    'guides.myGuides': 'Mis Guías',
    'guides.createGuide': '+ Crear Guía',
    'guides.noCustomGuides': 'Aún no has creado ninguna guía personalizada.',
    'guides.back': '← Volver',
    'guides.createCustomGuide': 'Crear Guía Personalizada',
    'guides.pathName': 'Nombre del Camino',
    'guides.pathNamePlaceholder': 'Ej: Mi Proyecto de Vida',
    'guides.description': 'Descripción',
    'guides.descriptionPlaceholder': 'Describe este camino...',
    'guides.philosophicalNote': 'Nota Filosófica (opcional)',
    'guides.philosophicalNotePlaceholder': 'Una breve reflexión sobre este camino...',
    'guides.fillNameDescription': 'Completa nombre y descripción',
    'guides.nodeStateLocked': 'Bloqueado',
    'guides.nodeStateAvailable': 'Disponible',
    'guides.nodeStateInProgress': 'En Progreso',
    'guides.nodeStateIntegrated': 'Integrado',
    'guides.nodeStateAbandoned': 'Abandonado',
    'guides.nodeTypeSkill': 'Habilidad',
    'guides.nodeTypeExperience': 'Experiencia',
    'guides.nodeTypeHabit': 'Hábito',
    'guides.nodeTypeChallenge': 'Desafío',
    'guides.nodeTypeReflection': 'Reflexión',
    'guides.nodeTypeKnowledge': 'Conocimiento',
    'common.editGoal': 'Editar Objetivo',
    'common.editAccountMoney': 'Editar Dinero en Cuenta',
    'common.editEntry': 'Editar Entrada',
    'common.editCategory': 'Editar Categoría',
    'common.editItem': 'Editar Elemento',
    'common.editList': 'Editar Lista',
    'common.newCategory': 'Nueva Categoría',
    'common.newItem': 'Nuevo Elemento',
    'common.newList': 'Nueva Lista Futura',
    'common.addStory': 'Agregar Historia',
    'common.clickToEdit': 'Haz clic para editar',
    'bio.noBioYet': 'Aún no hay biografía. Haz clic en "Editar" para agregar una.',
  },
  ja: {
    'footer.about': 'について',
    'footer.privacy': 'プライバシー',
    'footer.terms': '利用規約',
    'footer.language': '言語',
    'sections.habits': '習慣',
    'sections.journal': '日記',
    'sections.finances': '財務',
    'sections.goals': '目標',
    'sections.mapas': '地図',
    'sections.biography': '伝記',
    'sections.display': '表示',
    'sections.feedback': 'フィードバック',
    'sections.guides': 'ガイド',
    'about.title': 'について',
    'about.content1': 'Pixel Lifeは、習慣、目標、財務などを整理して追跡するのに役立つゲーム化されたライフ管理アプリケーションです。',
    'about.content2': 'ピクセル化された楽しいインターフェースで、日常のタスクを魅力的で動機付けとなる体験に変換します。',
    'privacy.title': 'プライバシー',
    'privacy.content1': 'あなたのプライバシーは私たちにとって重要です。このポリシーは、個人情報を収集、使用、保護する方法を説明しています。',
    'privacy.data': '収集されたデータ',
    'privacy.dataContent': '習慣データ、目標、パーソナライゼーション設定を含む、サービスを提供するために必要な情報のみを収集します。',
    'privacy.use': 'データの使用',
    'privacy.useContent': 'あなたのデータは、アプリケーション内の体験を改善するために排他的に使用され、第三者と共有されることはありません。',
    'terms.title': '利用規約',
    'terms.content1': 'Pixel Lifeを使用することで、以下の利用規約に同意したことになります。',
    'terms.use': 'アプリケーションの使用',
    'terms.useContent': 'あなたはアカウントの機密性を維持し、アカウントで発生するすべての活動に対して責任を負います。',
    'terms.liability': '責任の制限',
    'terms.liabilityContent': 'Pixel Lifeは、明示的または黙示的ないかなる種類の保証なしに「現状のまま」提供されます。',
    'display.myStats': 'マイ統計',
    'display.currentStreak': '現在の連続',
    'display.longestStreak': '最長連続',
    'display.trainings': 'トレーニング',
    'display.daysRegistered': '登録日数',
    'display.goalsCompleted': '完了した目標',
    'display.skillsMastered': '習得したスキル',
    'display.activeHabits': 'アクティブな習慣',
    'display.myProfile': 'マイプロフィール',
    'display.personalProfile': '個人プロフィール',
    'display.bio': '自己紹介:',
    'display.characters': '文字',
    'display.age': '年齢:',
    'display.city': '都市:',
    'display.title': 'タイトル:',
    'display.notInformed': '情報なし',
    'display.availableMoney': '利用可能なお金',
    'display.remainingLimit': '残りの制限',
    'display.reserve': '予備',
    'display.showRemainingLimit': '残りの制限を表示',
    'display.showAvailableMoney': '利用可能なお金を表示',
    'display.selectStatus': 'ステータスを選択',
    'display.changeStyle': 'スタイルを変更',
    'display.viewHistory': '履歴を表示',
    'display.achievements': '実績',
    'display.enterCity': '都市を入力',
    'display.titlePlaceholder': '例: 開発者、学生など',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.edit': '編集',
    'common.delete': '削除',
    'common.remove': '削除',
    'common.add': '追加',
    'common.addHabit': '習慣を追加',
    'common.newHabit': '新しい習慣',
    'common.renameHabit': '習慣の名前を変更',
    'common.habitName': '習慣名:',
    'common.newHabitName': '新しい習慣名:',
    'common.addEntry': 'エントリを追加',
    'common.saving': '保存中...',
    'common.confirm': '確認',
    'common.close': '閉じる',
    'common.yes': 'はい',
    'common.no': 'いいえ',
    'common.of': 'の',
    'common.selectDate': '日付を選択',
    'common.description': '説明',
    'common.value': '値',
    'common.date': '日付',
    'common.category': 'カテゴリ',
    'common.type': 'タイプ',
    'common.expense': '支出',
    'common.income': '収入',
    'common.removeConfirm': '削除',
    'common.deleteConfirm': '本当に削除しますか？',
    'common.confirmAction': 'アクションを確認',
    'common.addExpenseIncome': '支出/収入を追加',
    'common.editQuickThought': 'クイック思考を編集',
    'common.writeQuickThought': 'クイック思考を書く',
    'common.descriptionPlaceholder': '例: 材料の購入',
    'common.expenseIncome': '支出/収入',
    'common.gasto': '支出',
    'common.ganho': '収入',
    'journal.writeAboutDay': '今日のことを書いてください...',
    'journal.quickThoughts': 'クイック思考',
    'journal.longText': '長いテキスト',
    'journal.addQuickThought': '+ クイック思考を追加',
    'journal.noThoughtsThisMonth': '今月は思考が記録されていません',
    'journal.moodGood': '良い',
    'journal.moodNeutral': '普通',
    'journal.moodBad': '悪い',
    'journal.days': ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
    'journal.daysShort': ['日', '月', '火', '水', '木', '金', '土'],
    'journal.months': ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'journal.monthsFull': ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'journal.clickToAdd': '追加するにはクリック',
    'goals.type': 'タイプ',
    'goals.typeHouse': '家',
    'goals.typeVehicle': '車両',
    'goals.typeInvestment': '投資',
    'goals.typeEducation': '教育',
    'goals.typeCustom': 'カスタム',
    'goals.statusCompleted': '完了',
    'goals.statusInProgress': '進行中',
    'goals.statusLocked': 'ロック',
    'goals.orderBy': '並び替え',
    'goals.orderByValue': '値',
    'goals.orderByStatus': 'ステータス',
    'goals.orderByDate': '日付',
    'goals.orderAsc': '昇順',
    'goals.orderDesc': '降順',
    'mapas.categories': 'カテゴリ',
    'mapas.items': 'アイテム',
    'mapas.progress': '進捗',
    'biography.title': '伝記',
    'biography.addEvent': 'イベントを追加',
    'biography.timeline': 'タイムライン',
    'biography.dossiers': 'ファイル',
    'biography.aboutMe': '私について',
    'biography.noEventsYet': 'まだイベントがありません。ストーリーの記録を始めましょう！',
    'finances.daily': '日次',
    'finances.monthly': '月次',
    'finances.reserve': '予備金',
    'finances.monthlyLimit': '月間制限',
    'finances.accumulatedSpending': '累積支出',
    'finances.available': '利用可能',
    'finances.recommendedDaily': '推奨日次',
    'finances.statusBelowPace': 'ペース以下',
    'finances.statusAttention': '注意',
    'finances.statusAboveLimit': '制限超過',
    'finances.utilized': '使用済み',
    'finances.resetDay': 'リセット日',
    'finances.currentAccountMoney': 'アカウントの現在の金額',
    'finances.day': '日',
    'finances.details': '詳細',
    'finances.dailyTotal': '日次合計',
    'finances.remainingLimit': '残りの制限',
    'finances.accountMoney': 'アカウント金額',
    'finances.noEntriesRegistered': '登録されたエントリなし',
    'finances.addMovement': '取引を追加',
    'finances.totalReserve': '予備金合計',
    'finances.resetDayMustBe': 'リセット日は1日から31日の間である必要があります。',
    'goals.possessionsAndGoals': '所有物と目標',
    'goals.newGoal': '新しい目標',
    'goals.targetValue': '目標値 (R$)',
    'goals.completed': '完了',
    'goals.icon': 'アイコン:',
    'goals.descriptionPlaceholder': '例: 夢の家',
    'goals.create': '作成',
    'goals.current': '現在',
    'goals.target': '目標',
    'goals.accumulatedValue': '所有物の累積価値:',
    'common.history': '履歴',
    'common.hide': '非表示',
    'common.deposit': '預金',
    'common.withdrawal': '引出し',
    'common.status': 'ステータス:',
    'guides.title': 'ガイド — 可能な道',
    'guides.subtitle': '「正しい人生」は存在しません。可能な道があります。探索するものを選択してください。',
    'guides.officialGuides': '公式ガイド',
    'guides.loading': '公式ガイドを読み込み中... 新規ユーザーの場合、ガイドはまもなく初期化されます。',
    'guides.myGuides': 'マイガイド',
    'guides.createGuide': '+ ガイドを作成',
    'guides.noCustomGuides': 'まだカスタムガイドを作成していません。',
    'guides.back': '← 戻る',
    'guides.createCustomGuide': 'カスタムガイドを作成',
    'guides.pathName': 'パス名',
    'guides.pathNamePlaceholder': '例: 私の人生プロジェクト',
    'guides.description': '説明',
    'guides.descriptionPlaceholder': 'このパスを説明してください...',
    'guides.philosophicalNote': '哲学的ノート（オプション）',
    'guides.philosophicalNotePlaceholder': 'このパスに関する短い考察...',
    'guides.fillNameDescription': '名前と説明を入力してください',
    'guides.nodeStateLocked': 'ロック',
    'guides.nodeStateAvailable': '利用可能',
    'guides.nodeStateInProgress': '進行中',
    'guides.nodeStateIntegrated': '統合済み',
    'guides.nodeStateAbandoned': '放棄',
    'guides.nodeTypeSkill': 'スキル',
    'guides.nodeTypeExperience': '経験',
    'guides.nodeTypeHabit': '習慣',
    'guides.nodeTypeChallenge': '挑戦',
    'guides.nodeTypeReflection': '反省',
    'guides.nodeTypeKnowledge': '知識',
    'common.editGoal': '目標を編集',
    'common.editAccountMoney': 'アカウントのお金を編集',
    'common.editEntry': 'エントリを編集',
    'common.editCategory': 'カテゴリを編集',
    'common.editItem': 'アイテムを編集',
    'common.editList': 'リストを編集',
    'common.newCategory': '新しいカテゴリ',
    'common.newItem': '新しいアイテム',
    'common.newList': '新しい未来リスト',
    'common.addStory': 'ストーリーを追加',
    'common.clickToEdit': '編集するにはクリック',
    'bio.noBioYet': 'まだ自己紹介がありません。「編集」をクリックして追加してください。',
  },
  de: {
    'footer.about': 'ÜBER',
    'footer.privacy': 'DATENSCHUTZ',
    'footer.terms': 'NUTZUNGSBEDINGUNGEN',
    'footer.language': 'SPRACHE',
    'sections.habits': 'GEWOHNHEITEN',
    'sections.journal': 'TAGEBUCH',
    'sections.finances': 'FINANZEN',
    'sections.goals': 'ZIELE',
    'sections.mapas': 'KARTEN',
    'sections.biography': 'BIOGRAFIE',
    'sections.display': 'ANZEIGE',
    'sections.feedback': 'FEEDBACK',
    'sections.guides': 'ANLEITUNGEN',
    'about.title': 'ÜBER',
    'about.content1': 'Pixel Life ist eine gamifizierte Lebensverwaltungsanwendung, die Ihnen hilft, Ihre Gewohnheiten, Ziele, Finanzen und mehr zu organisieren und zu verfolgen.',
    'about.content2': 'Mit einer pixeligen und unterhaltsamen Benutzeroberfläche verwandeln wir alltägliche Aufgaben in ein ansprechendes und motivierendes Erlebnis.',
    'privacy.title': 'DATENSCHUTZ',
    'privacy.content1': 'Ihre Privatsphäre ist uns wichtig. Diese Richtlinie beschreibt, wie wir Ihre persönlichen Informationen sammeln, verwenden und schützen.',
    'privacy.data': 'Gesammelte Daten',
    'privacy.dataContent': 'Wir sammeln nur die Informationen, die zur Bereitstellung unserer Dienste erforderlich sind, einschließlich Gewohnheitsdaten, Ziele und Personalisierungseinstellungen.',
    'privacy.use': 'Verwendung von Daten',
    'privacy.useContent': 'Ihre Daten werden ausschließlich zur Verbesserung Ihrer Erfahrung in der Anwendung verwendet und nicht an Dritte weitergegeben.',
    'terms.title': 'NUTZUNGSBEDINGUNGEN',
    'terms.content1': 'Durch die Nutzung von Pixel Life stimmen Sie den folgenden Nutzungsbedingungen zu.',
    'terms.use': 'Verwendung der Anwendung',
    'terms.useContent': 'Sie sind für die Vertraulichkeit Ihres Kontos und für alle Aktivitäten verantwortlich, die unter Ihrem Konto auftreten.',
    'terms.liability': 'Haftungsbeschränkung',
    'terms.liabilityContent': 'Pixel Life wird "wie besehen" ohne Gewährleistungen jeglicher Art, ausdrücklich oder stillschweigend, bereitgestellt.',
    'display.myStats': 'MEINE STATISTIKEN',
    'display.currentStreak': 'Aktuelle Serie',
    'display.longestStreak': 'Längste Serie',
    'display.trainings': 'Trainings',
    'display.daysRegistered': 'Registrierte Tage',
    'display.goalsCompleted': 'Abgeschlossene Ziele',
    'display.skillsMastered': 'Gemeisterte Fähigkeiten',
    'display.activeHabits': 'Aktive Gewohnheiten',
    'display.myProfile': 'MEIN PROFIL',
    'display.personalProfile': 'Persönliches Profil',
    'display.bio': 'Bio:',
    'display.characters': 'Zeichen',
    'display.age': 'Alter:',
    'display.city': 'Stadt:',
    'display.title': 'Titel:',
    'display.notInformed': 'Nicht angegeben',
    'display.availableMoney': 'Verfügbares Geld',
    'display.remainingLimit': 'Verbleibendes Limit',
    'display.reserve': 'Reserve',
    'display.showRemainingLimit': 'Verbleibendes Limit anzeigen',
    'display.showAvailableMoney': 'Verfügbares Geld anzeigen',
    'display.selectStatus': 'Status auswählen',
    'display.changeStyle': 'Stil ändern',
    'display.viewHistory': 'Verlauf anzeigen',
    'display.achievements': 'Erfolge',
    'display.enterCity': 'Geben Sie Ihre Stadt ein',
    'display.titlePlaceholder': 'z.B. Entwickler, Student usw.',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.remove': 'Entfernen',
    'common.add': 'Hinzufügen',
    'common.addHabit': 'Gewohnheit hinzufügen',
    'common.newHabit': 'Neue Gewohnheit',
    'common.renameHabit': 'Gewohnheit umbenennen',
    'common.habitName': 'Gewohnheitsname:',
    'common.newHabitName': 'Neuer Gewohnheitsname:',
    'common.addEntry': 'Eintrag hinzufügen',
    'common.saving': 'Speichern...',
    'common.confirm': 'Bestätigen',
    'common.close': 'Schließen',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.of': 'von',
    'common.selectDate': 'Datum auswählen',
    'common.description': 'Beschreibung',
    'common.value': 'Wert',
    'common.date': 'Datum',
    'common.category': 'Kategorie',
    'common.type': 'Typ',
    'common.expense': 'Ausgabe',
    'common.income': 'Einkommen',
    'common.removeConfirm': 'Entfernen',
    'common.deleteConfirm': 'Möchten Sie dies wirklich löschen?',
    'common.confirmAction': 'Aktion bestätigen',
    'common.addExpenseIncome': 'Ausgabe/Einkommen hinzufügen',
    'common.editQuickThought': 'Schnellen Gedanken bearbeiten',
    'common.writeQuickThought': 'Einen schnellen Gedanken schreiben',
    'common.descriptionPlaceholder': 'z.B. Materialkauf',
    'common.expenseIncome': 'Ausgabe/Einkommen',
    'common.gasto': 'Ausgabe',
    'common.ganho': 'Einkommen',
    'journal.writeAboutDay': 'Schreibe über deinen Tag...',
    'journal.quickThoughts': 'SCHNELLE GEDANKEN',
    'journal.longText': 'Langer Text',
    'journal.addQuickThought': '+ Schnellen Gedanken hinzufügen',
    'journal.noThoughtsThisMonth': 'Dieser Monat wurden keine Gedanken aufgezeichnet',
    'journal.moodGood': 'Gut',
    'journal.moodNeutral': 'Neutral',
    'journal.moodBad': 'Schlecht',
    'journal.days': ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    'journal.daysShort': ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    'journal.months': ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
    'journal.monthsFull': ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
    'journal.clickToAdd': 'Zum Hinzufügen klicken',
    'goals.type': 'Typ',
    'goals.typeHouse': 'Haus',
    'goals.typeVehicle': 'Fahrzeug',
    'goals.typeInvestment': 'Investition',
    'goals.typeEducation': 'Bildung',
    'goals.typeCustom': 'Benutzerdefiniert',
    'goals.statusCompleted': 'Abgeschlossen',
    'goals.statusInProgress': 'In Bearbeitung',
    'goals.statusLocked': 'Gesperrt',
    'goals.statusPaused': 'Pausiert',
    'goals.orderBy': 'Sortieren nach',
    'goals.orderByValue': 'Wert',
    'goals.orderByStatus': 'Status',
    'goals.orderByDate': 'Datum',
    'goals.orderAsc': 'aufsteigend',
    'goals.orderDesc': 'absteigend',
    'mapas.categories': 'Kategorien',
    'mapas.items': 'Elemente',
    'mapas.progress': 'Fortschritt',
    'biography.title': 'Biografie',
    'biography.addEvent': 'Ereignis hinzufügen',
    'biography.timeline': 'Zeitleiste',
    'biography.dossiers': 'Dossiers',
    'biography.aboutMe': 'Über mich',
    'biography.noEventsYet': 'Noch keine Ereignisse. Beginnen Sie, Ihre Geschichte zu dokumentieren!',
    'finances.daily': 'Täglich',
    'finances.monthly': 'Monatlich',
    'finances.reserve': 'Reserve',
    'finances.monthlyLimit': 'Monatslimit',
    'finances.accumulatedSpending': 'Kumulierte Ausgaben',
    'finances.available': 'Verfügbar',
    'finances.recommendedDaily': 'Empfohlen Täglich',
    'finances.statusBelowPace': 'Unter dem Tempo',
    'finances.statusAttention': 'Aufmerksamkeit',
    'finances.statusAboveLimit': 'Über dem Limit',
    'finances.utilized': 'genutzt',
    'finances.resetDay': 'Zurücksetzungstag',
    'finances.currentAccountMoney': 'Aktuelles Geld auf dem Konto',
    'finances.day': 'Tag',
    'finances.details': 'Details',
    'finances.dailyTotal': 'Tagesgesamt',
    'finances.remainingLimit': 'Verbleibendes Limit',
    'finances.accountMoney': 'Geld auf dem Konto',
    'finances.noEntriesRegistered': 'Keine Einträge registriert',
    'finances.addMovement': 'Bewegung hinzufügen',
    'finances.totalReserve': 'Gesamtreserve',
    'finances.resetDayMustBe': 'Der Zurücksetzungstag muss zwischen 1 und 31 liegen.',
    'goals.possessionsAndGoals': 'Besitz und Ziele',
    'goals.newGoal': 'Neues Ziel',
    'goals.targetValue': 'Zielwert (R$)',
    'goals.completed': 'Abgeschlossen',
    'goals.icon': 'Symbol:',
    'goals.descriptionPlaceholder': 'z.B. Traumhaus',
    'goals.create': 'Erstellen',
    'goals.current': 'Aktuell',
    'goals.target': 'Ziel',
    'goals.accumulatedValue': 'Kumulierter Wert in Besitz:',
    'common.history': 'Verlauf',
    'common.hide': 'Verstecken',
    'common.deposit': 'Einzahlung',
    'common.withdrawal': 'Auszahlung',
    'common.status': 'Status:',
    'guides.title': 'Führer — Mögliche Wege',
    'guides.subtitle': 'Es gibt kein "richtiges Leben". Es gibt mögliche Wege. Wählen Sie, was Sie erkunden möchten.',
    'guides.officialGuides': 'Offizielle Führer',
    'guides.loading': 'Offizielle Führer werden geladen... Wenn Sie ein neuer Benutzer sind, werden die Führer in Kürze initialisiert.',
    'guides.myGuides': 'Meine Führer',
    'guides.createGuide': '+ Führer erstellen',
    'guides.noCustomGuides': 'Sie haben noch keine benutzerdefinierten Führer erstellt.',
    'guides.back': '← Zurück',
    'guides.createCustomGuide': 'Benutzerdefinierten Führer erstellen',
    'guides.pathName': 'Wegname',
    'guides.pathNamePlaceholder': 'z.B. Mein Lebensprojekt',
    'guides.description': 'Beschreibung',
    'guides.descriptionPlaceholder': 'Beschreiben Sie diesen Weg...',
    'guides.philosophicalNote': 'Philosophische Notiz (optional)',
    'guides.philosophicalNotePlaceholder': 'Eine kurze Überlegung zu diesem Weg...',
    'guides.fillNameDescription': 'Geben Sie Name und Beschreibung ein',
    'guides.nodeStateLocked': 'Gesperrt',
    'guides.nodeStateAvailable': 'Verfügbar',
    'guides.nodeStateInProgress': 'In Bearbeitung',
    'guides.nodeStateIntegrated': 'Integriert',
    'guides.nodeStateAbandoned': 'Aufgegeben',
    'guides.nodeTypeSkill': 'Fähigkeit',
    'guides.nodeTypeExperience': 'Erfahrung',
    'guides.nodeTypeHabit': 'Gewohnheit',
    'guides.nodeTypeChallenge': 'Herausforderung',
    'guides.nodeTypeReflection': 'Reflexion',
    'guides.nodeTypeKnowledge': 'Wissen',
    'common.editGoal': 'Ziel bearbeiten',
    'common.editAccountMoney': 'Kontogeld bearbeiten',
    'common.editEntry': 'Eintrag bearbeiten',
    'common.editCategory': 'Kategorie bearbeiten',
    'common.editItem': 'Element bearbeiten',
    'common.editList': 'Liste bearbeiten',
    'common.newCategory': 'Neue Kategorie',
    'common.newItem': 'Neues Element',
    'common.newList': 'Neue Zukunftsliste',
    'common.addStory': 'Geschichte hinzufügen',
    'common.clickToEdit': 'Zum Bearbeiten klicken',
    'bio.noBioYet': 'Noch keine Biografie. Klicken Sie auf "Bearbeiten", um eine hinzuzufügen.',
  },
  fr: {
    'footer.about': 'À PROPOS',
    'footer.privacy': 'CONFIDENTIALITÉ',
    'footer.terms': 'CONDITIONS',
    'footer.language': 'LANGUE',
    'sections.habits': 'HABITUDES',
    'sections.journal': 'JOURNAL',
    'sections.finances': 'FINANCES',
    'sections.goals': 'OBJECTIFS',
    'sections.mapas': 'CARTES',
    'sections.biography': 'BIOGRAPHIE',
    'sections.display': 'AFFICHAGE',
    'sections.feedback': 'RETOUR',
    'sections.guides': 'GUIDES',
    'about.title': 'À PROPOS',
    'about.content1': 'Pixel Life est une application de gestion de vie gamifiée qui vous aide à organiser et suivre vos habitudes, objectifs, finances et plus encore.',
    'about.content2': 'Avec une interface pixélisée et amusante, nous transformons les tâches quotidiennes en une expérience engageante et motivante.',
    'privacy.title': 'CONFIDENTIALITÉ',
    'privacy.content1': 'Votre vie privée est importante pour nous. Cette politique décrit comment nous collectons, utilisons et protégeons vos informations personnelles.',
    'privacy.data': 'Données Collectées',
    'privacy.dataContent': 'Nous ne collectons que les informations nécessaires pour fournir nos services, y compris les données d\'habitudes, les objectifs et les préférences de personnalisation.',
    'privacy.use': 'Utilisation des Données',
    'privacy.useContent': 'Vos données sont utilisées exclusivement pour améliorer votre expérience dans l\'application et ne sont pas partagées avec des tiers.',
    'terms.title': 'CONDITIONS',
    'terms.content1': 'En utilisant Pixel Life, vous acceptez les conditions d\'utilisation suivantes.',
    'terms.use': 'Utilisation de l\'Application',
    'terms.useContent': 'Vous êtes responsable de maintenir la confidentialité de votre compte et de toutes les activités qui se produisent sous votre compte.',
    'terms.liability': 'Limitation de Responsabilité',
    'terms.liabilityContent': 'Pixel Life est fourni "tel quel", sans garanties d\'aucune sorte, expresses ou implicites.',
    'display.myStats': 'MES STATISTIQUES',
    'display.currentStreak': 'Série Actuelle',
    'display.longestStreak': 'Plus Longue Série',
    'display.trainings': 'Entraînements',
    'display.daysRegistered': 'Jours Enregistrés',
    'display.goalsCompleted': 'Objectifs Complétés',
    'display.skillsMastered': 'Compétences Maîtrisées',
    'display.activeHabits': 'Habitudes Actives',
    'display.myProfile': 'MON PROFIL',
    'display.personalProfile': 'Profil Personnel',
    'display.bio': 'Bio:',
    'display.characters': 'caractères',
    'display.age': 'Âge:',
    'display.city': 'Ville:',
    'display.title': 'Titre:',
    'display.notInformed': 'Non renseigné',
    'display.availableMoney': 'Argent Disponible',
    'display.remainingLimit': 'Limite Restante',
    'display.reserve': 'Réserve',
    'display.showRemainingLimit': 'Afficher Limite Restante',
    'display.showAvailableMoney': 'Afficher Argent Disponible',
    'display.selectStatus': 'Sélectionner le Statut',
    'display.changeStyle': 'Changer le Style',
    'display.viewHistory': 'Voir l\'Historique',
    'display.achievements': 'Réalisations',
    'display.enterCity': 'Entrez votre ville',
    'display.titlePlaceholder': 'Ex: Développeur, Étudiant, etc.',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.remove': 'Retirer',
    'common.add': 'Ajouter',
    'common.addHabit': 'Ajouter Habitude',
    'common.newHabit': 'Nouvelle habitude',
    'common.renameHabit': 'Renommer l\'habitude',
    'common.habitName': 'Nom de l\'habitude:',
    'common.newHabitName': 'Nouveau nom de l\'habitude:',
    'common.addEntry': 'Ajouter Entrée',
    'common.saving': 'Enregistrement...',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.of': 'de',
    'common.selectDate': 'Sélectionner la date',
    'common.description': 'Description',
    'common.value': 'Valeur',
    'common.date': 'Date',
    'common.category': 'Catégorie',
    'common.type': 'Type',
    'common.expense': 'Dépense',
    'common.income': 'Revenu',
    'common.removeConfirm': 'Retirer',
    'common.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cela?',
    'common.confirmAction': 'Confirmer l\'action',
    'common.addExpenseIncome': 'Ajouter Dépense/Revenu',
    'common.editQuickThought': 'Modifier pensée rapide',
    'common.writeQuickThought': 'Écrire une pensée rapide',
    'common.descriptionPlaceholder': 'Ex: Achat de matériel',
    'common.expenseIncome': 'Dépense/Revenu',
    'common.gasto': 'Dépense',
    'common.ganho': 'Revenu',
    'journal.writeAboutDay': 'Écrivez sur votre journée...',
    'journal.quickThoughts': 'PENSÉES RAPIDES',
    'journal.longText': 'Texte Long',
    'journal.addQuickThought': '+ Ajouter une pensée rapide',
    'journal.noThoughtsThisMonth': 'Aucune pensée enregistrée ce mois-ci',
    'journal.moodGood': 'Bien',
    'journal.moodNeutral': 'Neutre',
    'journal.moodBad': 'Mal',
    'journal.days': ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
    'journal.daysShort': ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
    'journal.months': ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
    'journal.monthsFull': ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
    'journal.clickToAdd': 'Cliquez pour ajouter',
    'goals.type': 'Type',
    'goals.typeHouse': 'Maison',
    'goals.typeVehicle': 'Véhicule',
    'goals.typeInvestment': 'Investissement',
    'goals.typeEducation': 'Éducation',
    'goals.typeCustom': 'Personnalisé',
    'goals.statusCompleted': 'Terminé',
    'goals.statusInProgress': 'En Cours',
    'goals.statusLocked': 'Verrouillé',
    'goals.statusPaused': 'En Pause',
    'goals.orderBy': 'Trier par',
    'goals.orderByValue': 'Valeur',
    'goals.orderByStatus': 'Statut',
    'goals.orderByDate': 'Date',
    'goals.orderAsc': 'croissant',
    'goals.orderDesc': 'décroissant',
    'mapas.categories': 'Catégories',
    'mapas.items': 'Éléments',
    'mapas.progress': 'Progrès',
    'biography.title': 'Biographie',
    'biography.addEvent': 'Ajouter un Événement',
    'biography.timeline': 'Chronologie',
    'biography.dossiers': 'Dossiers',
    'biography.aboutMe': 'À Propos de Moi',
    'biography.noEventsYet': 'Aucun événement pour le moment. Commencez à enregistrer votre histoire !',
    'finances.daily': 'Quotidien',
    'finances.monthly': 'Mensuel',
    'finances.reserve': 'Réserve',
    'finances.monthlyLimit': 'Limite Mensuelle',
    'finances.accumulatedSpending': 'Dépenses Accumulées',
    'finances.available': 'Disponible',
    'finances.recommendedDaily': 'Quotidien Recommandé',
    'finances.statusBelowPace': 'En dessous du rythme',
    'finances.statusAttention': 'Attention',
    'finances.statusAboveLimit': 'Au-dessus de la limite',
    'finances.utilized': 'utilisé',
    'finances.resetDay': 'Jour de réinitialisation',
    'finances.currentAccountMoney': 'Argent actuel en compte',
    'finances.day': 'Jour',
    'finances.details': 'Détails',
    'finances.dailyTotal': 'Total Quotidien',
    'finances.remainingLimit': 'Limite Restante',
    'finances.accountMoney': 'Argent en Compte',
    'finances.noEntriesRegistered': 'Aucune entrée enregistrée',
    'finances.addMovement': 'Ajouter un Mouvement',
    'finances.totalReserve': 'Total de la Réserve',
    'finances.resetDayMustBe': 'Le jour de réinitialisation doit être entre 1 et 31.',
    'goals.possessionsAndGoals': 'Possessions et Objectifs',
    'goals.newGoal': 'Nouvel Objectif',
    'goals.targetValue': 'Valeur Cible (R$)',
    'goals.completed': 'Terminé',
    'goals.icon': 'Icône:',
    'goals.descriptionPlaceholder': 'Ex: Maison de rêve',
    'goals.create': 'Créer',
    'goals.current': 'Actuel',
    'goals.target': 'Cible',
    'goals.accumulatedValue': 'Valeur accumulée en possessions:',
    'common.history': 'Historique',
    'common.hide': 'Masquer',
    'common.deposit': 'Dépôt',
    'common.withdrawal': 'Retrait',
    'common.status': 'Statut:',
    'guides.title': 'Guides — Chemins Possibles',
    'guides.subtitle': 'Il n\'y a pas de "vie correcte". Il y a des chemins possibles. Choisissez ce que vous voulez explorer.',
    'guides.officialGuides': 'Guides Officiels',
    'guides.loading': 'Chargement des guides officiels... Si vous êtes un nouvel utilisateur, les guides seront initialisés sous peu.',
    'guides.myGuides': 'Mes Guides',
    'guides.createGuide': '+ Créer un Guide',
    'guides.noCustomGuides': 'Vous n\'avez pas encore créé de guides personnalisés.',
    'guides.back': '← Retour',
    'guides.createCustomGuide': 'Créer un Guide Personnalisé',
    'guides.pathName': 'Nom du Chemin',
    'guides.pathNamePlaceholder': 'Ex: Mon Projet de Vie',
    'guides.description': 'Description',
    'guides.descriptionPlaceholder': 'Décrivez ce chemin...',
    'guides.philosophicalNote': 'Note Philosophique (optionnel)',
    'guides.philosophicalNotePlaceholder': 'Une courte réflexion sur ce chemin...',
    'guides.fillNameDescription': 'Remplissez le nom et la description',
    'guides.nodeStateLocked': 'Verrouillé',
    'guides.nodeStateAvailable': 'Disponible',
    'guides.nodeStateInProgress': 'En Cours',
    'guides.nodeStateIntegrated': 'Intégré',
    'guides.nodeStateAbandoned': 'Abandonné',
    'guides.nodeTypeSkill': 'Compétence',
    'guides.nodeTypeExperience': 'Expérience',
    'guides.nodeTypeHabit': 'Habitude',
    'guides.nodeTypeChallenge': 'Défi',
    'guides.nodeTypeReflection': 'Réflexion',
    'guides.nodeTypeKnowledge': 'Connaissance',
    'common.editGoal': 'Modifier l\'Objectif',
    'common.editAccountMoney': 'Modifier l\'Argent du Compte',
    'common.editEntry': 'Modifier l\'Entrée',
    'common.editCategory': 'Modifier la Catégorie',
    'common.editItem': 'Modifier l\'Élément',
    'common.editList': 'Modifier la Liste',
    'common.newCategory': 'Nouvelle Catégorie',
    'common.newItem': 'Nouvel Élément',
    'common.newList': 'Nouvelle Liste Future',
    'common.addStory': 'Ajouter une Histoire',
    'common.clickToEdit': 'Cliquer pour modifier',
    'bio.noBioYet': 'Pas encore de biographie. Cliquez sur "Modifier" pour en ajouter une.',
  },
  it: {
    'footer.about': 'CHI SIAMO',
    'footer.privacy': 'PRIVACY',
    'footer.terms': 'TERMINI',
    'footer.language': 'LINGUA',
    'sections.habits': 'ABITUDINI',
    'sections.journal': 'DIARIO',
    'sections.finances': 'FINANZE',
    'sections.goals': 'OBIETTIVI',
    'sections.mapas': 'MAPPE',
    'sections.biography': 'BIOGRAFIA',
    'sections.display': 'VISUALIZZAZIONE',
    'sections.feedback': 'FEEDBACK',
    'sections.guides': 'GUIDE',
    'about.title': 'CHI SIAMO',
    'about.content1': 'Pixel Life è un\'applicazione di gestione della vita gamificata che ti aiuta a organizzare e tracciare le tue abitudini, obiettivi, finanze e altro ancora.',
    'about.content2': 'Con un\'interfaccia pixelata e divertente, trasformiamo le attività quotidiane in un\'esperienza coinvolgente e motivante.',
    'privacy.title': 'PRIVACY',
    'privacy.content1': 'La tua privacy è importante per noi. Questa politica descrive come raccogliamo, utilizziamo e proteggiamo le tue informazioni personali.',
    'privacy.data': 'Dati Raccolti',
    'privacy.dataContent': 'Raccogliamo solo le informazioni necessarie per fornire i nostri servizi, inclusi dati sulle abitudini, obiettivi e preferenze di personalizzazione.',
    'privacy.use': 'Uso dei Dati',
    'privacy.useContent': 'I tuoi dati vengono utilizzati esclusivamente per migliorare la tua esperienza nell\'applicazione e non sono condivisi con terze parti.',
    'terms.title': 'TERMINI',
    'terms.content1': 'Utilizzando Pixel Life, accetti i seguenti termini di utilizzo.',
    'terms.use': 'Uso dell\'Applicazione',
    'terms.useContent': 'Sei responsabile di mantenere la riservatezza del tuo account e per tutte le attività che si verificano sotto il tuo account.',
    'terms.liability': 'Limitazione di Responsabilità',
    'terms.liabilityContent': 'Pixel Life è fornito "così com\'è", senza garanzie di alcun tipo, espresse o implicite.',
    'display.myStats': 'LE MIE STATISTICHE',
    'display.currentStreak': 'Serie Attuale',
    'display.longestStreak': 'Serie Più Lunga',
    'display.trainings': 'Allenamenti',
    'display.daysRegistered': 'Giorni Registrati',
    'display.goalsCompleted': 'Obiettivi Completati',
    'display.skillsMastered': 'Abilità Padroneggiate',
    'display.activeHabits': 'Abitudini Attive',
    'display.myProfile': 'IL MIO PROFILO',
    'display.personalProfile': 'Profilo Personale',
    'display.bio': 'Bio:',
    'display.characters': 'caratteri',
    'display.age': 'Età:',
    'display.city': 'Città:',
    'display.title': 'Titolo:',
    'display.notInformed': 'Non informato',
    'display.availableMoney': 'Denaro Disponibile',
    'display.remainingLimit': 'Limite Rimanente',
    'display.reserve': 'Riserva',
    'display.showRemainingLimit': 'Mostra Limite Rimanente',
    'display.showAvailableMoney': 'Mostra Denaro Disponibile',
    'display.selectStatus': 'Seleziona Stato',
    'display.changeStyle': 'Cambia Stile',
    'display.viewHistory': 'Visualizza Cronologia',
    'display.achievements': 'Risultati',
    'display.enterCity': 'Inserisci la tua città',
    'display.titlePlaceholder': 'Es: Sviluppatore, Studente, ecc.',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.edit': 'Modifica',
    'common.delete': 'Elimina',
    'common.remove': 'Rimuovi',
    'common.add': 'Aggiungi',
    'common.addHabit': 'Aggiungi Abitudine',
    'common.newHabit': 'Nuova abitudine',
    'common.renameHabit': 'Rinomina abitudine',
    'common.habitName': 'Nome abitudine:',
    'common.newHabitName': 'Nuovo nome abitudine:',
    'common.addEntry': 'Aggiungi Voce',
    'common.saving': 'Salvataggio...',
    'common.confirm': 'Conferma',
    'common.close': 'Chiudi',
    'common.yes': 'Sì',
    'common.no': 'No',
    'common.of': 'di',
    'common.selectDate': 'Seleziona data',
    'common.description': 'Descrizione',
    'common.value': 'Valore',
    'common.date': 'Data',
    'common.category': 'Categoria',
    'common.type': 'Tipo',
    'common.expense': 'Spesa',
    'common.income': 'Reddito',
    'common.removeConfirm': 'Rimuovi',
    'common.deleteConfirm': 'Sei sicuro di voler eliminare questo?',
    'common.confirmAction': 'Conferma azione',
    'common.addExpenseIncome': 'Aggiungi Spesa/Reddito',
    'common.editQuickThought': 'Modifica pensiero rapido',
    'common.writeQuickThought': 'Scrivi un pensiero rapido',
    'common.descriptionPlaceholder': 'Es: Acquisto materiale',
    'common.expenseIncome': 'Spesa/Reddito',
    'common.gasto': 'Spesa',
    'common.ganho': 'Reddito',
    'journal.writeAboutDay': 'Scrivi della tua giornata...',
    'journal.quickThoughts': 'PENSIERI RAPIDI',
    'journal.longText': 'Testo Lungo',
    'journal.addQuickThought': '+ Aggiungi pensiero rapido',
    'journal.noThoughtsThisMonth': 'Nessun pensiero registrato questo mese',
    'journal.moodGood': 'Buono',
    'journal.moodNeutral': 'Neutrale',
    'journal.moodBad': 'Cattivo',
    'journal.days': ['Domenica', 'Lunedì', 'Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato'],
    'journal.daysShort': ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
    'journal.months': ['Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic'],
    'journal.monthsFull': ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'],
    'journal.clickToAdd': 'Clicca per aggiungere',
    'goals.type': 'Tipo',
    'goals.typeHouse': 'Casa',
    'goals.typeVehicle': 'Veicolo',
    'goals.typeInvestment': 'Investimento',
    'goals.typeEducation': 'Educazione',
    'goals.typeCustom': 'Personalizzato',
    'goals.statusCompleted': 'Completato',
    'goals.statusInProgress': 'In Corso',
    'goals.statusLocked': 'Bloccato',
    'goals.statusPaused': 'In Pausa',
    'goals.orderBy': 'Ordina per',
    'goals.orderByValue': 'Valore',
    'goals.orderByStatus': 'Stato',
    'goals.orderByDate': 'Data',
    'goals.orderAsc': 'crescente',
    'goals.orderDesc': 'decrescente',
    'mapas.categories': 'Categorie',
    'mapas.items': 'Elementi',
    'mapas.progress': 'Progresso',
    'biography.title': 'Biografia',
    'biography.addEvent': 'Aggiungi Evento',
    'biography.timeline': 'Cronologia',
    'biography.dossiers': 'Dossier',
    'biography.aboutMe': 'Su di Me',
    'biography.noEventsYet': 'Nessun evento ancora. Inizia a registrare la tua storia!',
    'finances.daily': 'Giornaliero',
    'finances.monthly': 'Mensile',
    'finances.reserve': 'Riserva',
    'finances.monthlyLimit': 'Limite Mensile',
    'finances.accumulatedSpending': 'Spesa Accumulata',
    'finances.available': 'Disponibile',
    'finances.recommendedDaily': 'Giornaliero Consigliato',
    'finances.statusBelowPace': 'Sotto il ritmo',
    'finances.statusAttention': 'Attenzione',
    'finances.statusAboveLimit': 'Sopra il limite',
    'finances.utilized': 'utilizzato',
    'finances.resetDay': 'Giorno di reset',
    'finances.currentAccountMoney': 'Denaro attuale in conto',
    'finances.day': 'Giorno',
    'finances.details': 'Dettagli',
    'finances.dailyTotal': 'Totale Giornaliero',
    'finances.remainingLimit': 'Limite Rimanente',
    'finances.accountMoney': 'Denaro in Conto',
    'finances.noEntriesRegistered': 'Nessuna voce registrata',
    'finances.addMovement': 'Aggiungi Movimento',
    'finances.totalReserve': 'Totale della Riserva',
    'finances.resetDayMustBe': 'Il giorno di reset deve essere tra 1 e 31.',
    'goals.possessionsAndGoals': 'Possedimenti e Obiettivi',
    'goals.newGoal': 'Nuovo Obiettivo',
    'goals.targetValue': 'Valore Obiettivo (R$)',
    'goals.completed': 'Completato',
    'goals.icon': 'Icona:',
    'goals.descriptionPlaceholder': 'Es: Casa dei sogni',
    'goals.create': 'Crea',
    'goals.current': 'Attuale',
    'goals.target': 'Obiettivo',
    'goals.accumulatedValue': 'Valore accumulato in possessi:',
    'common.history': 'Cronologia',
    'common.hide': 'Nascondi',
    'common.deposit': 'Deposito',
    'common.withdrawal': 'Prelievo',
    'common.status': 'Stato:',
    'guides.title': 'Guide — Percorsi Possibili',
    'guides.subtitle': 'Non esiste una "vita giusta". Esistono percorsi possibili. Scegli cosa esplorare.',
    'guides.officialGuides': 'Guide Ufficiali',
    'guides.loading': 'Caricamento guide ufficiali... Se sei un nuovo utente, le guide verranno inizializzate a breve.',
    'guides.myGuides': 'Le Mie Guide',
    'guides.createGuide': '+ Crea Guida',
    'guides.noCustomGuides': 'Non hai ancora creato nessuna guida personalizzata.',
    'guides.back': '← Indietro',
    'guides.createCustomGuide': 'Crea Guida Personalizzata',
    'guides.pathName': 'Nome del Percorso',
    'guides.pathNamePlaceholder': 'Es: Il Mio Progetto di Vita',
    'guides.description': 'Descrizione',
    'guides.descriptionPlaceholder': 'Descrivi questo percorso...',
    'guides.philosophicalNote': 'Nota Filosofica (opzionale)',
    'guides.philosophicalNotePlaceholder': 'Una breve riflessione su questo percorso...',
    'guides.fillNameDescription': 'Compila nome e descrizione',
    'guides.nodeStateLocked': 'Bloccato',
    'guides.nodeStateAvailable': 'Disponibile',
    'guides.nodeStateInProgress': 'In Corso',
    'guides.nodeStateIntegrated': 'Integrato',
    'guides.nodeStateAbandoned': 'Abbandonato',
    'guides.nodeTypeSkill': 'Abilità',
    'guides.nodeTypeExperience': 'Esperienza',
    'guides.nodeTypeHabit': 'Abitudine',
    'guides.nodeTypeChallenge': 'Sfida',
    'guides.nodeTypeReflection': 'Riflessione',
    'guides.nodeTypeKnowledge': 'Conoscenza',
    'common.editGoal': 'Modifica Obiettivo',
    'common.editAccountMoney': 'Modifica Denaro Conto',
    'common.editEntry': 'Modifica Voce',
    'common.editCategory': 'Modifica Categoria',
    'common.editItem': 'Modifica Elemento',
    'common.editList': 'Modifica Lista',
    'common.newCategory': 'Nuova Categoria',
    'common.newItem': 'Nuovo Elemento',
    'common.newList': 'Nuova Lista Futura',
    'common.addStory': 'Aggiungi Storia',
    'common.clickToEdit': 'Clicca per modificare',
    'bio.noBioYet': 'Nessuna biografia ancora. Clicca su "Modifica" per aggiungerne una.',
  },
  'zh-CN': {
    'footer.about': '关于',
    'footer.privacy': '隐私',
    'footer.terms': '条款',
    'footer.language': '语言',
    'sections.habits': '习惯',
    'sections.journal': '日记',
    'sections.finances': '财务',
    'sections.goals': '目标',
    'sections.mapas': '地图',
    'sections.biography': '传记',
    'sections.display': '显示',
    'sections.feedback': '反馈',
    'sections.guides': '指南',
    'about.title': '关于',
    'about.content1': 'Pixel Life 是一款游戏化的生活管理应用程序，可帮助您组织和跟踪您的习惯、目标、财务等。',
    'about.content2': '通过像素化和有趣的界面，我们将日常任务转变为引人入胜且激励人心的体验。',
    'privacy.title': '隐私',
    'privacy.content1': '您的隐私对我们很重要。本政策描述了我们如何收集、使用和保护您的个人信息。',
    'privacy.data': '收集的数据',
    'privacy.dataContent': '我们仅收集提供服务所需的信息，包括习惯数据、目标和个性化偏好。',
    'privacy.use': '数据使用',
    'privacy.useContent': '您的数据仅用于改善您在应用程序中的体验，不会与第三方共享。',
    'terms.title': '条款',
    'terms.content1': '使用 Pixel Life 即表示您同意以下使用条款。',
    'terms.use': '应用程序使用',
    'terms.useContent': '您有责任维护您帐户的机密性，并对您帐户下发生的所有活动负责。',
    'terms.liability': '责任限制',
    'terms.liabilityContent': 'Pixel Life 按"原样"提供，不提供任何明示或暗示的保证。',
    'display.myStats': '我的统计',
    'display.currentStreak': '当前连续',
    'display.longestStreak': '最长连续',
    'display.trainings': '训练',
    'display.daysRegistered': '注册天数',
    'display.goalsCompleted': '已完成目标',
    'display.skillsMastered': '掌握的技能',
    'display.activeHabits': '活跃习惯',
    'display.myProfile': '我的资料',
    'display.personalProfile': '个人资料',
    'display.bio': '简介:',
    'display.characters': '字符',
    'display.age': '年龄:',
    'display.city': '城市:',
    'display.title': '头衔:',
    'display.notInformed': '未提供',
    'display.availableMoney': '可用资金',
    'display.remainingLimit': '剩余限额',
    'display.reserve': '储备',
    'display.showRemainingLimit': '显示剩余限额',
    'display.showAvailableMoney': '显示可用资金',
    'display.selectStatus': '选择状态',
    'display.changeStyle': '更改样式',
    'display.viewHistory': '查看历史',
    'display.achievements': '成就',
    'display.enterCity': '输入您的城市',
    'display.titlePlaceholder': '例如：开发者、学生等',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.remove': '移除',
    'common.add': '添加',
    'common.addHabit': '添加习惯',
    'common.newHabit': '新习惯',
    'common.renameHabit': '重命名习惯',
    'common.habitName': '习惯名称:',
    'common.newHabitName': '新习惯名称:',
    'common.addEntry': '添加条目',
    'common.saving': '保存中...',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.yes': '是',
    'common.no': '否',
    'common.of': '的',
    'common.selectDate': '选择日期',
    'common.description': '描述',
    'common.value': '值',
    'common.date': '日期',
    'common.category': '类别',
    'common.type': '类型',
    'common.expense': '支出',
    'common.income': '收入',
    'common.removeConfirm': '移除',
    'common.deleteConfirm': '您确定要删除吗？',
    'common.confirmAction': '确认操作',
    'common.addExpenseIncome': '添加支出/收入',
    'common.editQuickThought': '编辑快速想法',
    'common.writeQuickThought': '写一个快速想法',
    'common.descriptionPlaceholder': '例如：材料购买',
    'common.expenseIncome': '支出/收入',
    'common.gasto': '支出',
    'common.ganho': '收入',
    'journal.writeAboutDay': '写下你的一天...',
    'journal.quickThoughts': '快速想法',
    'journal.longText': '长文本',
    'journal.addQuickThought': '+ 添加快速想法',
    'journal.noThoughtsThisMonth': '本月未记录任何想法',
    'journal.moodGood': '好',
    'journal.moodNeutral': '中性',
    'journal.moodBad': '坏',
    'journal.days': ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
    'journal.daysShort': ['日', '一', '二', '三', '四', '五', '六'],
    'journal.months': ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'journal.monthsFull': ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'journal.clickToAdd': '点击添加',
    'goals.type': '类型',
    'goals.typeHouse': '房屋',
    'goals.typeVehicle': '车辆',
    'goals.typeInvestment': '投资',
    'goals.typeEducation': '教育',
    'goals.typeCustom': '自定义',
    'goals.statusCompleted': '已完成',
    'goals.statusInProgress': '进行中',
    'goals.statusLocked': '已锁定',
    'goals.statusPaused': '已暂停',
    'goals.orderBy': '排序方式',
    'goals.orderByValue': '价值',
    'goals.orderByStatus': '状态',
    'goals.orderByDate': '日期',
    'goals.orderAsc': '升序',
    'goals.orderDesc': '降序',
    'mapas.categories': '类别',
    'mapas.items': '项目',
    'mapas.progress': '进度',
    'biography.title': '传记',
    'biography.addEvent': '添加事件',
    'biography.timeline': '时间线',
    'biography.dossiers': '档案',
    'biography.aboutMe': '关于我',
    'biography.noEventsYet': '还没有事件。开始记录你的故事吧！',
    'finances.daily': '每日',
    'finances.monthly': '每月',
    'finances.reserve': '储备',
    'finances.monthlyLimit': '月度限额',
    'finances.accumulatedSpending': '累计支出',
    'finances.available': '可用',
    'finances.recommendedDaily': '推荐每日',
    'finances.statusBelowPace': '低于节奏',
    'finances.statusAttention': '注意',
    'finances.statusAboveLimit': '超过限额',
    'finances.utilized': '已使用',
    'finances.resetDay': '重置日',
    'finances.currentAccountMoney': '账户当前金额',
    'finances.day': '日',
    'finances.details': '详情',
    'finances.dailyTotal': '每日总计',
    'finances.remainingLimit': '剩余限额',
    'finances.accountMoney': '账户金额',
    'finances.noEntriesRegistered': '没有注册的条目',
    'finances.addMovement': '添加交易',
    'finances.totalReserve': '总储备',
    'finances.resetDayMustBe': '重置日必须在1到31之间。',
    'goals.possessionsAndGoals': '财产和目标',
    'goals.newGoal': '新目标',
    'goals.targetValue': '目标值 (R$)',
    'goals.completed': '已完成',
    'goals.icon': '图标:',
    'goals.descriptionPlaceholder': '例如：梦想之家',
    'goals.create': '创建',
    'goals.current': '当前',
    'goals.target': '目标',
    'goals.accumulatedValue': '拥有资产累计价值:',
    'common.history': '历史',
    'common.hide': '隐藏',
    'common.deposit': '存款',
    'common.withdrawal': '取款',
    'common.status': '状态:',
    'guides.title': '指南 — 可能的路径',
    'guides.subtitle': '没有"正确的生活"。有可能的路径。选择要探索的内容。',
    'guides.officialGuides': '官方指南',
    'guides.loading': '正在加载官方指南... 如果您是新用户，指南将很快初始化。',
    'guides.myGuides': '我的指南',
    'guides.createGuide': '+ 创建指南',
    'guides.noCustomGuides': '您还没有创建任何自定义指南。',
    'guides.back': '← 返回',
    'guides.createCustomGuide': '创建自定义指南',
    'guides.pathName': '路径名称',
    'guides.pathNamePlaceholder': '例如：我的人生项目',
    'guides.description': '描述',
    'guides.descriptionPlaceholder': '描述此路径...',
    'guides.philosophicalNote': '哲学笔记（可选）',
    'guides.philosophicalNotePlaceholder': '关于此路径的简短思考...',
    'guides.fillNameDescription': '填写名称和描述',
    'guides.nodeStateLocked': '已锁定',
    'guides.nodeStateAvailable': '可用',
    'guides.nodeStateInProgress': '进行中',
    'guides.nodeStateIntegrated': '已集成',
    'guides.nodeStateAbandoned': '已放弃',
    'guides.nodeTypeSkill': '技能',
    'guides.nodeTypeExperience': '经验',
    'guides.nodeTypeHabit': '习惯',
    'guides.nodeTypeChallenge': '挑战',
    'guides.nodeTypeReflection': '反思',
    'guides.nodeTypeKnowledge': '知识',
    'common.editGoal': '编辑目标',
    'common.editAccountMoney': '编辑账户资金',
    'common.editEntry': '编辑条目',
    'common.editCategory': '编辑类别',
    'common.editItem': '编辑项目',
    'common.editList': '编辑列表',
    'common.newCategory': '新类别',
    'common.newItem': '新项目',
    'common.newList': '新未来列表',
    'common.addStory': '添加故事',
    'common.clickToEdit': '点击编辑',
    'bio.noBioYet': '还没有简介。点击"编辑"添加一个。',
  },
  'zh-TW': {
    'footer.about': '關於',
    'footer.privacy': '隱私',
    'footer.terms': '條款',
    'footer.language': '語言',
    'sections.habits': '習慣',
    'sections.journal': '日記',
    'sections.finances': '財務',
    'sections.goals': '目標',
    'sections.mapas': '地圖',
    'sections.biography': '傳記',
    'sections.display': '顯示',
    'sections.feedback': '反饋',
    'sections.guides': '指南',
    'about.title': '關於',
    'about.content1': 'Pixel Life 是一款遊戲化的生活管理應用程式，可幫助您組織和追蹤您的習慣、目標、財務等。',
    'about.content2': '透過像素化和有趣的介面，我們將日常任務轉變為引人入勝且激勵人心的體驗。',
    'privacy.title': '隱私',
    'privacy.content1': '您的隱私對我們很重要。本政策描述我們如何收集、使用和保護您的個人資訊。',
    'privacy.data': '收集的資料',
    'privacy.dataContent': '我們僅收集提供服務所需的資訊，包括習慣資料、目標和個人化偏好。',
    'privacy.use': '資料使用',
    'privacy.useContent': '您的資料僅用於改善您在應用程式中的體驗，不會與第三方共享。',
    'terms.title': '條款',
    'terms.content1': '使用 Pixel Life 即表示您同意以下使用條款。',
    'terms.use': '應用程式使用',
    'terms.useContent': '您有責任維護您帳戶的機密性，並對您帳戶下發生的所有活動負責。',
    'terms.liability': '責任限制',
    'terms.liabilityContent': 'Pixel Life 按"原樣"提供，不提供任何明示或暗示的保證。',
    'display.myStats': '我的統計',
    'display.currentStreak': '目前連續',
    'display.longestStreak': '最長連續',
    'display.trainings': '訓練',
    'display.daysRegistered': '註冊天數',
    'display.goalsCompleted': '已完成目標',
    'display.skillsMastered': '掌握的技能',
    'display.activeHabits': '活躍習慣',
    'display.myProfile': '我的資料',
    'display.personalProfile': '個人資料',
    'display.bio': '簡介:',
    'display.characters': '字元',
    'display.age': '年齡:',
    'display.city': '城市:',
    'display.title': '頭銜:',
    'display.notInformed': '未提供',
    'display.availableMoney': '可用資金',
    'display.remainingLimit': '剩餘限額',
    'display.reserve': '儲備',
    'display.showRemainingLimit': '顯示剩餘限額',
    'display.showAvailableMoney': '顯示可用資金',
    'display.selectStatus': '選擇狀態',
    'display.changeStyle': '更改樣式',
    'display.viewHistory': '查看歷史',
    'display.achievements': '成就',
    'display.enterCity': '輸入您的城市',
    'display.titlePlaceholder': '例如：開發者、學生等',
    'common.save': '儲存',
    'common.cancel': '取消',
    'common.edit': '編輯',
    'common.delete': '刪除',
    'common.remove': '移除',
    'common.add': '新增',
    'common.addHabit': '新增習慣',
    'common.newHabit': '新習慣',
    'common.renameHabit': '重新命名習慣',
    'common.habitName': '習慣名稱:',
    'common.newHabitName': '新習慣名稱:',
    'common.addEntry': '新增項目',
    'common.saving': '儲存中...',
    'common.confirm': '確認',
    'common.close': '關閉',
    'common.yes': '是',
    'common.no': '否',
    'common.description': '描述',
    'common.value': '值',
    'common.date': '日期',
    'common.category': '類別',
    'common.type': '類型',
    'common.expense': '支出',
    'common.income': '收入',
    'common.removeConfirm': '移除',
    'common.deleteConfirm': '您確定要刪除嗎？',
    'common.confirmAction': '確認操作',
    'common.addExpenseIncome': '新增支出/收入',
    'common.editQuickThought': '編輯快速想法',
    'common.writeQuickThought': '寫一個快速想法',
    'common.descriptionPlaceholder': '例如：材料購買',
    'common.expenseIncome': '支出/收入',
    'common.gasto': '支出',
    'common.ganho': '收入',
    'journal.writeAboutDay': '寫下你的一天...',
    'journal.quickThoughts': '快速想法',
    'journal.longText': '長文本',
    'journal.addQuickThought': '+ 新增快速想法',
    'journal.noThoughtsThisMonth': '本月未記錄任何想法',
    'journal.moodGood': '好',
    'journal.moodNeutral': '中性',
    'journal.moodBad': '壞',
    'journal.days': ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
    'journal.daysShort': ['日', '一', '二', '三', '四', '五', '六'],
    'journal.months': ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'journal.monthsFull': ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    'journal.clickToAdd': '点击添加',
    'goals.type': '類型',
    'goals.typeHouse': '房屋',
    'goals.typeVehicle': '車輛',
    'goals.typeInvestment': '投資',
    'goals.typeEducation': '教育',
    'goals.typeCustom': '自訂',
    'goals.statusCompleted': '已完成',
    'goals.statusInProgress': '進行中',
    'goals.statusLocked': '已鎖定',
    'goals.statusPaused': '已暫停',
    'goals.orderBy': '排序方式',
    'goals.orderByValue': '價值',
    'goals.orderByStatus': '狀態',
    'goals.orderByDate': '日期',
    'goals.orderAsc': '升序',
    'goals.orderDesc': '降序',
    'mapas.categories': '類別',
    'mapas.items': '項目',
    'mapas.progress': '進度',
    'biography.title': '傳記',
    'biography.addEvent': '新增事件',
    'biography.timeline': '時間線',
    'biography.dossiers': '檔案',
    'biography.aboutMe': '關於我',
    'biography.noEventsYet': '還沒有事件。開始記錄你的故事吧！',
    'finances.daily': '每日',
    'finances.monthly': '每月',
    'finances.reserve': '儲備',
    'finances.monthlyLimit': '月度限額',
    'finances.accumulatedSpending': '累計支出',
    'finances.available': '可用',
    'finances.recommendedDaily': '推薦每日',
    'finances.statusBelowPace': '低於節奏',
    'finances.statusAttention': '注意',
    'finances.statusAboveLimit': '超過限額',
    'finances.utilized': '已使用',
    'finances.resetDay': '重置日',
    'finances.currentAccountMoney': '帳戶當前金額',
    'finances.day': '日',
    'finances.details': '詳情',
    'finances.dailyTotal': '每日總計',
    'finances.remainingLimit': '剩餘限額',
    'finances.accountMoney': '帳戶金額',
    'finances.noEntriesRegistered': '沒有註冊的條目',
    'finances.addMovement': '新增交易',
    'finances.totalReserve': '總儲備',
    'finances.resetDayMustBe': '重置日必須在1到31之間。',
    'goals.possessionsAndGoals': '財產和目標',
    'goals.newGoal': '新目標',
    'goals.targetValue': '目標值 (R$)',
    'goals.completed': '已完成',
    'goals.icon': '圖標:',
    'goals.descriptionPlaceholder': '例如：夢想之家',
    'goals.create': '創建',
    'goals.current': '當前',
    'goals.target': '目標',
    'common.history': '歷史',
    'common.hide': '隱藏',
    'common.deposit': '存款',
    'common.withdrawal': '取款',
    'common.status': '狀態:',
    'guides.title': '指南 — 可能的路徑',
    'guides.subtitle': '沒有"正確的生活"。有可能的路徑。選擇要探索的內容。',
    'guides.officialGuides': '官方指南',
    'guides.loading': '正在載入官方指南... 如果您是新用戶，指南將很快初始化。',
    'guides.myGuides': '我的指南',
    'guides.createGuide': '+ 新增指南',
    'guides.noCustomGuides': '您還沒有建立任何自訂指南。',
    'guides.back': '← 返回',
    'guides.createCustomGuide': '建立自訂指南',
    'guides.pathName': '路徑名稱',
    'guides.pathNamePlaceholder': '例如：我的人生專案',
    'guides.description': '描述',
    'guides.descriptionPlaceholder': '描述此路徑...',
    'guides.philosophicalNote': '哲學筆記（選填）',
    'guides.philosophicalNotePlaceholder': '關於此路徑的簡短思考...',
    'guides.fillNameDescription': '填寫名稱和描述',
    'guides.nodeStateLocked': '已鎖定',
    'guides.nodeStateAvailable': '可用',
    'guides.nodeStateInProgress': '進行中',
    'guides.nodeStateIntegrated': '已整合',
    'guides.nodeStateAbandoned': '已放棄',
    'guides.nodeTypeSkill': '技能',
    'guides.nodeTypeExperience': '經驗',
    'guides.nodeTypeHabit': '習慣',
    'guides.nodeTypeChallenge': '挑戰',
    'guides.nodeTypeReflection': '反思',
    'guides.nodeTypeKnowledge': '知識',
    'common.editGoal': '編輯目標',
    'common.editAccountMoney': '編輯帳戶資金',
    'common.editEntry': '編輯項目',
    'common.editCategory': '編輯類別',
    'common.editItem': '編輯項目',
    'common.editList': '編輯清單',
    'common.newCategory': '新類別',
    'common.newItem': '新項目',
    'common.newList': '新未來清單',
    'common.addStory': '新增故事',
    'common.clickToEdit': '點擊編輯',
    'bio.noBioYet': '還沒有簡介。點擊"編輯"新增一個。',
  },
};

const languageNames: Record<Language, string> = {
  en: 'English',
  ko: '한국어',
  pt: 'Português (BR)',
  es: 'Español',
  ja: '日本語',
  de: 'Deutsch',
  fr: 'Français',
  it: 'Italiano',
  'zh-CN': '简体中文',
  'zh-TW': '繁體中文',
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pt');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Armazena o timestamp da mudança de idioma para delay de tradução
    if (typeof window !== 'undefined') {
      localStorage.setItem('languageChangeTime', Date.now().toString());
    }
  };

  const t = (key: string): string | string[] => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const tString = (key: string): string => {
    const value = t(key);
    return Array.isArray(value) ? value.join(', ') : value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tString }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { languageNames };

